### ISSUE TITLE
3D Synch Lost

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1004]
After changing the axes variables, I hovered over a new point and brought up the 3D surface viewer.  Although the synch button was pressed, rotating the new view didn't change the older views.  I suspect that the focus didn't transition to the new view properly since after clicking the 3D synch button on and off and messing with the views, once the synch restarted, it showed the view from one of the other viewers.

**Comment by pjcross** [comment]
I've changed my theory on what is happening to synch between viewers.  Plus I see that the same problem is present with both 3D and video synch.  In both cases, the problem is not that synch stops working or that the focus isn't right, it is that at some point in pressing the synch button the icon flashes but doesn't change to reflect the correct state.  After that, pressing the synch button does flip the state of the icon, but now it does not reflect the state of synchronization.  The tooltip does reflect the correct state, as does the behavior of the viewers.  The only thing that is off is the icon being displayed.  If you close all the views and bring up at least two viewers, assuming synch was off, then push the synch button, it will flash and be out of synch after that.  Further toggles of the synch button seem to work properly, so there is something about the initial press that is different.  I suspect that it has to do with the video/3D panel being hidden when there are no viewers and the interaction between it being just drawn and the first push of the synch button.

**Comment by alexsielicki** [comment]
This was caused by Bootstrap updating its button component to automatically update its attributes based on user clicks. It interferred with React's updates, thus causing toggle buttons' state to be wrong after toggling.
