### ISSUE TITLE
Actions Dropdown Disabled

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1020]
I have selected and pulled a set of videos in the Parameter Space Model (Firefox on Mac).  Once all of the videos are loaded in the view, the Actions button turns grey and its functions are unavailable (including, close all pins).  I can make the drop down active again by closing one of the video views, but if I bring it back using Pin Selected Items, then the drop down is disabled again.

**Comment by alexsielicki** [comment]
Filters need to be open for this to happen.

**Comment by pjcross** [comment]
Turns out that the 3D Viewer example that I sent you is also dependent on filters being open.
