### ISSUE TITLE
Resizing Video Window Doesn't Terminate

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1021]
When resizing video viewers in the Parameter Space model (Firefox on Mac), if the lower right corner of the viewer being resized overlaps another viewer, the button release is lost.  Even releasing and reclicking doesn't register the release.  Instead, it starts playing the other video (the one it is overlapping).  Clicking again stops the video, but still doesn't terminate the resizing operation.  The resize can be terminated by making the viewer large enough or small enough that the lower right corner is outside the other viewer's boundary, then releasing.  Or moving the mouse over the background and clicking will terminate the operation, though this will result in a yellow rubberband selection operation that then needs to be terminated.  Plus, this loses the selected points.  This issue is not present when resizing the 3D viewer.

**Comment by alexsielicki** [comment]
This happens in Chrome too, but only if I release the resize handle while it's over the other video's controls bar across the bottom.

**Comment by alexsielicki** [comment]
This happens with PDFs too. But does **not** happen with other types, specifically images, CVS, 3D, or STL. Only happens with videos and PDFs when releasing (mouseup) over the viewer while the mouse pointer is outside the resizing frame's resize handle. Common thing is that videos and PDFs use the browser's built in media viewer that has its own controls. 3D and STL are viewers with controls but not native to the browser. Image viewer is native but no controls. CVS is just plain text with a link.
