### ISSUE TITLE
Remote host specification

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1024]
When selecting a remote host in the Timeseries wizard (and I suspect also the VideoSwarm wizard), the hosts in the config file appear as a dropdown list of choices.  We suspect that when selecting from this list, the server recognizes any of these choices as being a remote host that will have agent software installed.  Selecting one of these will cause that agent code to be launched.  However, we have discovered that when one of these same machines are specified by giving the full path with xxx.sandia.gov being entered by the user, the system does not recognize that this is a known machine with agent code.  Although you can still login and still navigate directories, without the agent code running any parallel job launching will fail.

Since we wish to enable users to access remote hosts that are not on the list, it is unclear how to best handle this situation.  Perhaps we need to restrict the remote host access for wizards generating models that require parallel processing.  Or perhaps the launching code needs to send an error message back to the user that they have tried to launch a job from a system that doesn't have an agent running (and to make the comment that individually specified hosts won't launch agents).  Perhaps we need to be able to map the longer specification back to our list (perhaps through a list of alias permutations?).

**Comment by Mletter1** [comment]
closing until proven to be an issue
