### ISSUE TITLE
Timeseries Wizard Markings

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1025]
If the user leaves the model with the Markings Not Applied choice, you get the following error:
![image](https://user-images.githubusercontent.com/4998608/122109057-2c9d4100-cdda-11eb-80b3-17716354fa75.png)

This is one of the list on the dropdown of choices, so it shouldn't produce an error.  And I do think that it should be a choice, rather than forcing people to decide between options that they aren't sure about.

**Comment by pjcross** [comment]
Also, when a model is in this state, you can't delete it until you choose a marking that it recognizes.  This should not prevent model deletion.

**Comment by pjcross** [comment]
Though once the model is finished being generated, I can select 'Markings Not Applied' without a problem.  It is only a problem during the time that the parallel job is running.

**Comment by Mletter1** [comment]
this is fixed
