### ISSUE TITLE
Need newer Node and/or npm in docker before Oct 4 2021

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#1033]
npm is complaining about connections and I think we just need to upgrade the version of Node inside docker. I did a quick search of the code and didn't find how to do that. Here's the warning message:

`npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/`

**Comment by alexsielicki** [comment]
@pjcross I think this is the issue you're seeing in your local docker

**Comment by Mletter1** [comment]
@pjcross @alexsielicki  lets just monitor this for now

**Comment by pjcross** [comment]
Broke my Docker build

**Comment by pjcross** [comment]
Docker builds now.
