### ISSUE TITLE
Cannot change drive in Windows share session

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1035]
Once I pick a collaborative drive, I can never get back to the field to specify the drive again, even if I start the wizard again.  I should be able to see that field, both if I click the back button, or if I restart the wizard.  Additionally, once I've made a connection, I am unable to see how to terminate it, so I'm blocked from making any other (different) connection.

**Comment by Mletter1** [comment]
this has been added and you can now change between share drives
