### ISSUE TITLE
CCA wizard scrolling broken for long variable list (Firefox on Mac)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1040]
I have a long list of variables and accidentally made them all outputs.  I got the error message that I need at least one input variable, but I'd lost my scrolling capability to get back to the top of the list (the inputs were no longer visible).  I clicked the back button and then went forward again.  The list was reset to the top, but everything was marked as an input now and scrolling to see the variables at the bottom of the list no longer worked.  I'm not sure how I got all outputs initially, since the default is for everything to be inputs (maybe I accidentally selected the first line of the list instead of the first line of the outputs when I did my shift click to select the list).  However, I've repeated making sure that there was an error to get the error popup to make sure it is reproducible.  The scrolling is lost once the error popup appears.  Otherwise (without an error), the scrolling works just fine.

**Comment by pjcross** [comment]
Actually, CCA is breaking once I get past the parsing...

**Comment by pjcross** [comment]
The scrolling bug after the error popup is present irrespective of whether the input file is local or remote.  However, the model failure is limited to the remote option.

**Comment by alexsielicki** [comment]
Seems like we have 2 bugs here. I'm starting on the modal scrolling issues first. Looks like when the second modal closes, it removes the "modal-open" class from the body element, thus breaking scrolling in the first modal. Working on a fix for this now.

**Comment by alexsielicki** [comment]
Second bug is that CCA model fails to create. For me this only happened when I used the local option for uploading data. Remote worked just fine for same data file. Here's the traceback:

```
Traceback (most recent call last):
  File "/usr/src/slycat/slycat/web-server/plugins/slycat-cca/slycat-cca.py", line 93, in compute
    slycat.web.server.put_model_arrayset_data(database, model, "cca-statistics", "0/0/...;0/1/...", [r, wilks])
  File "/usr/src/slycat/slycat/packages/slycat/web/server/__init__.py", line 420, in put_model_arrayset_data
    hdf5_array.set_data(attribute.expression.index, hyperslice, data_hyperslice)
  File "/usr/src/slycat/slycat/packages/slycat/hdf5.py", line 204, in set_data
    attribute_storage[hyperslice] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 939, in __setitem__
    mspace = h5s.create_simple(selection.expand_shape(mshape))
  File "/usr/local/lib/python3.7/site-packages/h5py/_hl/selections.py", line 264, in expand_shape
    raise TypeError("Can't broadcast %s -> %s" % (source_shape, self.array_shape))  # array shape
TypeError: Can't broadcast (0,) -> (2,)
```

@Mletter1 or @Spurs20 does this mean anything to either of you?

**Comment by alexsielicki** [comment]
Turns out the error is due to the fact that data columns were being repeated in my test file. This is unlikely to come up in user data, so we will not check for this condition.
