### ISSUE TITLE
Restore state of pins when re-opening pins

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#1043]
For 3D pins, restore:

1. Rotation, zoom, etc
2. Color By variable

For cloned pins, save state of last closed pin, not last pin that was interacted with. So save state on pin close, not on pin interaction.

For video pins, restore time of video.

For all pins, restore size and location.

**Comment by pjcross** [comment]
The loss of Color by Variable when restoring a hidden point with a 3D viewer is described in issue #1001.
