### ISSUE TITLE
Time series wizard hangs for Xyce and CSV input

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1046]
The timeseries wizard hangs after the last step of naming the model.  It doesn't not advance to the page for tracking the progress of the parallel job.  This happens for both Xyce and CSV input table types.

**Comment by pjcross** [comment]
Look at related issue #1039.

**Comment by Mletter1** [comment]
This is currently working on master and can complete a timeseries model

**Comment by pjcross** [comment]
I just tested it on Qual, it doesn't work.
