### ISSUE TITLE
Windows share drive back button 

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1047]
When I click the back button after logging into the Collab1 drive to change my login to the Collab2 drive, the directory list shown for the Collab2 is the same as I saw for the Collab1 drive.  I suspect that I haven't actually changed drives.

**Comment by pjcross** [comment]
However, when I exit the wizard and start over, it has remembered my session (no password prompt) and now I see the Collab2 drive directory list, which is different.

**Comment by Mletter1** [comment]
This has to do with react remembering state variables and not reseting them between logins, but if you closed the wizard state is reset to blank and makes it so this issue goes away.
