### ISSUE TITLE
CCA Model Wizard Fails for Tables > 1000 Rows and Columns with Strings

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1050]
The same parsing issue (#1045 ) is also in the CCA wizard.  The wizard hangs for tables with more than 1000 rows and with string columns.

**Comment by Mletter1** [comment]
This might have to do with the upgrade to a new python. Also we can check out couch to see if thats an issue

**Comment by pjcross** [comment]
Fixed.
