### ISSUE TITLE
Parsing for CCA and Parameter Space models fails for 15K CSV data  for Remote Source

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1057]
This only fails for files read from the cluster, not for the same file read from a local disk.  A popup appears with the following message: 
Alert
Did you choose the correct file and filetype?  There was a problem parsing the file: undefined

**Comment by pjcross** [comment]
This is not a function of the number of rows.  The 26K row Covid data set can be ingested from a remote source without failing.

**Comment by Mletter1** [comment]
solution found and is nearly comleted

**Comment by pjcross** [comment]
Fixed.
