### ISSUE TITLE
Identical Headers in Parameter Space

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#1058]
I just waited about 20 minutes to upload the Covid data set into a parameter space model.  It finished, but the model creation appears to be hung now.  There were identical headers in the CSV.  Although it is good that the parser let me know that it had found this, it appears that I now need to go back into the CSV and modify the headers to be unique, then start over with a new upload.  Why can't we notify the user of the issue, tell them that we are renaming the columns to xxxx1 and xxxx2, then finish the model creation?

![image](https://user-images.githubusercontent.com/4998608/139945660-b987c105-e123-4ca7-bdd7-46139d32f89b.png)

**Comment by Mletter1** [comment]
I don't think we should change data tagging for removal.
