### ISSUE TITLE
Reset Model functionality should be available to reader role

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#1063]
@wlhunt reported in #468

> Also some edit button functions, such as Reset Model, should always be available as long as the user has read access to the project. Currently the edit button is not displayed for non-writers, and thereby removes the reset model feature.

**Comment by alexsielicki** [comment]
This is fairly easy to do, but moves the 'Reset Model' menu item from the 'Edit' menu to the 'Info' menu for everyone. My initial thought is that this isn't a problem, since it does not actually edit anything, just changes the state of the model. What does everyone else think?

**Comment by wlhunt** [comment]
Yep, move the Reset Model to Info. Of the available choices, Info seems best.
