### ISSUE TITLE
provide solution for popped-up media with transparent areas or background

### ISSUE THREAD

**Issue by wlhunt** [sandialabs/slycat#1119]
Automatically placing a black background under an image with transparency can cause the text and axis to be indistinguishable. Perhaps make the BG gray, or give the user a choice.

**Comment by alexsielicki** [comment]
Perhaps a checkered background with white and gray, so there isn't a single color that could be the same.

**Comment by alexsielicki** [comment]
Checkerboard background is often used in image editing software to convey transparency, but this doesn't work in our application. Example below. Note the illegible white text in the lower left of each frame.

<img width="1050" alt="image" src="https://github.com/sandialabs/slycat/assets/66206/8cf0e143-799c-4353-b2e7-9a8deb168c81">

**Comment by alexsielicki** [comment]
@wlhunt I think this was completed a while back so I'm closing this issue. Please reopen if you think it needs more work.
