### ISSUE TITLE
slycat agent writing unidentified files

### ISSUE THREAD

**Issue by wlhunt** [sandialabs/slycat#1138]
Upon starting a remote slurm job, such as a timeseries job, the slycat agent writes anonymous files in the user's home directory.  Files should be written with a clear filename and within the identified work directory.  These files are currently named something like 12345678.log (where the 8 digit number varies).

**Comment by Mletter1** [comment]
tag 719357d0b

**Comment by Mletter1** [comment]
closed with #1141
