### ISSUE TITLE
Need info for username on SMB login modal

### ISSUE THREAD

**Issue by Mletter1** [sandialabs/slycat#1142]
Add something like an info bullet or something that says "username may require domain to be appended eg. username@domain.com

**Comment by wlhunt** [comment]
or perhaps fancier, where Slycat detects the env and adds the at domain, if the user didn't add it

**Comment by Mletter1** [comment]
As we discussed we will add it to the config file and populate the login with it

**Comment by Mletter1** [comment]
update the docs as well

**Comment by Spurs20** [comment]
Closed - restructuring of SMB login wizard makes this no longer relevant.
