### ISSUE TITLE
Lost sorting icons for all columns

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#146]
Only happened once and can't figure out how to trigger it again.  It was not a question of waiting long enough, since I changed the color-coding in the scatterplot a couple of times and it did update.

**Comment by pjcross** [comment]
I haven't seen this again.  We have speculated that it might have been related to the connection count issue, which has now been fixed, so I'm closing this.

**Comment by pjcross** [comment]
OK.  Now this is reproducable. When I change the Y variable, it loses the div for the sorting icon.

**Comment by pjcross** [comment]
I'm trying to remember if this earlier version of the bug was on the CCA model rather than the PS model.  If so, there is no Y axis selection and this current bug might be something entirely different.

**Comment by alexsielicki** [comment]
This is also affecting Parameter Image, so reopening.
