### ISSUE TITLE
Remove GET Model Array Attribute Chunk.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/slycat#174]
There's no reason to have multiple APIs for retrieving data.  This will be obsoleted by GET Model Arrayset Data.

**Comment by Mletter1** [comment]
82f9ea9d1963acb13b0e306215e10f09ad53870e

**Comment by Mletter1** [comment]
see 82f9ea9d1963acb13b0e306215e10f09ad53870e for pattern to update endpoints

**Comment by Mletter1** [comment]
Currently waiting to see if we need to updated tracer image model or if we should skip it

**Comment by Mletter1** [comment]
we are skipping it but keeping the code around

**Comment by Mletter1** [comment]
decided to update the tracer image model for consistency.

**Comment by Mletter1** [comment]
found another spot that needs this update.

**Comment by Mletter1** [comment]
This is open until fully remove from cluster plugin

**Comment by Mletter1** [comment]
keep the deprecated api but wont support
