### ISSUE TITLE
Color Legend Rectangle Height Redundantly Calculated/Overwritten

### ISSUE THREAD

**Issue by lustrousgorilla** [sandialabs/slycat#218]
It's the case in the tracer model and thus almost certainly also in the PI model. Look at these if clauses in the scatterplots jquery widget: updates["render_legend"] and updates["update_legend_position"].

**Comment by Mletter1** [comment]
Need to see if this is still going on

**Comment by pjcross** [comment]
I cannot see any issues in the Parameter Space model legend.  The Tracer model is gone.  Since I don't know what it was referring to, I'm going to close this.
