### ISSUE TITLE
Move the Parameter Image user interface into its plugin.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/slycat#285]
This should be completed as soon as possible *after* the projects-navbar branch is merged with master.

**Comment by alexsielicki** [comment]
I believe @lustrousgorilla is working on this, so reassigned to him.

**Comment by lustrousgorilla** [comment]
Done. Started with the PIM from PIMP since @alexsielicki said it had the most recent changes from the pim-fixes branch.
