### ISSUE TITLE
Selection in sparklines not drawn when changing dendrogram tabs

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#288]
Although the selection is not lost, when I switch between dendrograms, the highlighted simulation is retained in both the table and the waveform view, but lost in the dendrogram until something else is selected.  Then the 3 views are linked in what they are displaying.  I'm seeing this in Firefox on Windows.

**Comment by alexsielicki** [comment]
We need to bookmark row selection once and have it apply across clusters.
