### ISSUE TITLE
Timeseries legend gradient disappears when legend is hidden then shown

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#296]
The gradient for the timeseries legend disappears under these conditions:
1. Hide the entire legend by collapsing its pane.
2. Switch selected variables by clicking on a table header.
3. Show the entire legend by expanding its pane.

This happens in Firefox and is probably related to the svg gradient bug I ran across under different contexts.

**Comment by pjcross** [comment]
I see it in Firefox on Windows, but not in Chrome.

**Comment by alexsielicki** [comment]
This appears not only when switching selected variables, but also when doing anything else that updates the bookmark, such as switching colors, selecting a different dendrogram node, selecting a different waveform, etc. all while the legend pane is collapsed.
