### ISSUE TITLE
Y axis change lost selected points in Chrome on Windows 7

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#315]
I'd had a number of points selected (and they remained selected in the other 3 graphs), but when I changed the variable for the Y axis, it produced a single point near the origin, which no longer matches the other graphs.

**Comment by pjcross** [comment]
![image](https://cloud.githubusercontent.com/assets/4998608/5821091/c552a512-a086-11e4-9f55-c9f010fc9ade.png)
Here is an image of the bug.

**Comment by pjcross** [comment]
I believe that the trigger for the mismatched points is that inbetween the selection of the point(s) and changing the variable for the axis, I mouse over the graph line and pull an image.  The incorrectly selected point corresponds to the image that just was pulled.

**Comment by lustrousgorilla** [comment]
That was extremely helpful Pat. Looking into it now.
