### ISSUE TITLE
Table sorting icon (triangle) disappeared after sorting in Chrome on OS X

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#316]
I sorted the table based on the Time column.  The sorting icon disappeared and never reappeared, although when I hover over where it should be, I get the ascending/descending tool tip and can click and perform another sort.  So I think only the icon is lost, not the functionality.
![screen shot 2015-01-20 at 4 59 00 pm](https://cloud.githubusercontent.com/assets/4998608/5828815/47b5e502-a0c6-11e4-9f07-13e2940408cf.png)

**Comment by pjcross** [comment]
I can get the icon back when I sort on a different column, though that new column then loses its sorting icon.

**Comment by pjcross** [comment]
I'm also seeing this on Firefox on Windows 7

**Comment by lustrousgorilla** [comment]
@pjcross, I noticed and fixed this yesterday.
