### ISSUE TITLE
Dual images of two sizes in one image frame (chrome on OS X)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#318]
I'm not sure how I get into this state, but it has happened to me more than once.  I have two different-sized versions of the same image superimposed.  The smaller image is in the upper left and the two versions form an 'L'-shape, with the graph visible behind them in the crook of the 'L'.  I see two copies of the pin icon, though only the one for the larger image is operational, and it is being drawn on top of the graph, as though the upper right corner of the image were transparent.  I cannot resize this image, nor do I see the resize icon, though I do see the other two (pin and delete, both of which work).

**Comment by FadingSwordsman** [comment]
How to reproduce:
1. Display an image, move it to save the bookmark
2. Scroll over to display the same image again, move again to save the bookmark
3. Reload latest bookmark

Only one box is displayed with two images in it.
We would expect both images to display separately, in their own frames.

**Comment by FadingSwordsman** [comment]
Fixed in master

**Comment by pjcross** [comment]
I just experienced this again.  This time I just pinned the image after bringing it up on hover.

**Comment by FadingSwordsman** [comment]
Can reproduce -- Moving from one point to another very quickly causes both event handlers to fire at once, which causes them to try and build the same frame at the same time. Working on resolving this.
