### ISSUE TITLE
Create a knockout-based virtual grid component.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/slycat#329]
Requirements:
- It must retrieve ranges of columns efficiently (this is where slickgrid doesn't scale - it retrieves every column for a range of rows).
- It must be easily parameterized (IMO, this is where most grids fail - they try to do too much, the parameterization gets needlessly complex, and it becomes difficult to workaround "default" behavior).

**Comment by tshead2** [comment]
Proposed API:

* Specify number of rows and columns.
* Specify row heights and column widths.
* Specify a callback function for creating per-cell markup.
* Specify per-row / per-column / per-cell class changes.
* Invalidate ranges of rows / columns / cells.
* Specify fixed cells?

**Comment by lustrousgorilla** [comment]
@tshead2 - https://rniemeyer.github.io/knockout-kendo/web/Grid.html, https://github.com/Knockout-Contrib/KoGrid, http://wijmo.com/grid-with-knockout-viewmodel-loading-remote-data/, http://grid.tesseris.com/Home/DemoKnockout - would one of these do the trick?

**Comment by tshead2** [comment]
@lustrousgorilla -These suffer from the same limitations as slickGrid - the number of rows is limited by the maximum size of a div, and the number of columns is assumed to be relatively small, generally < 100.  While it doesn't come-up for TI, or PI, we've had issues with those limitations in CCA and timeseries models before.  My goal is a grid that supports 1B x 1B cells.

**Comment by Mletter1** [comment]
This will be removed as we will be going to a new paradigm for our web server web client architecture
