### ISSUE TITLE
Create a "remap URI" wizard.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/slycat#334]
The problem: users create PI models pointing to data accessed via URI on a particular host / filesystem.  If the host goes away, or the filesystem is renamed, etc. the model breaks.

The solution: create a wizard to remap an existing PI model's data to a different host / filesystem.

**Comment by srbdev** [comment]
@pjcross @tshead2 were you able to get feedback from the users for the remap URL interface? If not, should I leave this ticket open for now or go ahead and close it?
