### ISSUE TITLE
Variable left off of bar chart (Chrome on Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#339]
The 2nd to last variable name is rather long and is written using two lines in the bar chart.  This has pushed the final variable name out of sight.  Selecting the 2nd to last variable highlights the long name and its associated row in the bar chart. Clicking on the bar chart's final row highlights its line, though the highlight of the associated name is just a few pixels at the bottom of the list (the text is not visible).  This layout issue doesn't happen in Firefox, which maintains the single row mapping by allowing enough width to display the long variable name on one line.

**Comment by pjcross** [comment]
The source of the problem was that I had changed my scaling in the browser and Chrome is not correctly passing back the right coordinates to the client.  This is the source of many of the Chrome bugs I have found (i.e. resetting the scale fixes them).

**Comment by Mletter1** [comment]
Chrome has gone through many upgrades, unlikely still going on.
