### ISSUE TITLE
Load Error opening PIP model.

### ISSUE THREAD

**Issue by tshead2** [sandialabs/slycat#341]
* Create a PIP model using sample data generated by slycat-create-sample-parameter-image-csv.py.
* Open the model in Slycat.
* There is a single Load Error modal when the model is opened.  However, there aren't any failed AJAX requests in the browser debugger or console error messages.
* The dendrogram pane isn't populated.

**Comment by tshead2** [comment]
I verified that this issue occurs whether or not the user specifies input and output columns when creating the model.

**Comment by alexsielicki** [comment]
I tried to reproduce in Chrome and FF under OSX and the model loads just fine for me. Can I come look at it on your machine @tshead2 ?

**Comment by alexsielicki** [comment]
@tshead2 are you still seeing this problem or can I close it?

**Comment by alexsielicki** [comment]
I don't think this is happening anymore, so closing.
