### ISSUE TITLE
Once login cancelled, no way to get dialog back 

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#345]
Once the user cancels out of the remote login dialog, there is no way to get back to it later.  If the previous bookmark included pinned images, this strands them without icons, so they can't be deleted.  Additionally, new images are brought up as white squares, but they cannot be viewed.  We need to offer the dialog again.

**Comment by FadingSwordsman** [comment]
Mostly done other than some minor annoyances. On cancelling a login dialog, all of the images display an exclamation.
Clicking on that makes the login dialog appear again.

**Comment by pjcross** [comment]
I was wondering if maybe a reload icon (the circular arrow) might be more expressive of the operation being performed than an exclamation.

**Comment by FadingSwordsman** [comment]
The circular 'refresh' arrow is now in place, instead.

On reopening the dialog, all images which will be loaded after completion are now changed to the loading icon.
