### ISSUE TITLE
Movie frame lacks controls and cannot be deleted (Firefox and Chrome on Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#357]
I have a test case with 2 movies.  After bringing up the first movie and playing it, I hover over the 2nd movie's point and bring it up and play it.  The first movie never went away.  Although I can now play both, they overlap and lack icons for pinning or deleting them.  I cannot move them around to separate them, nor can I get rid of either of them.

**Comment by pjcross** [comment]
Whichever one is the current focus displays outlines on both the left and right sides of the frame.  These end rectangles had originally been white and contained the pin and delete icons.

**Comment by alexsielicki** [comment]
Fixed
