### ISSUE TITLE
PI creation dialog next button not accessible when zoomed (Firefox OSX)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#360]
When using the create remote PI model dialog, I'd zoomed in to enlarge the text.  The number of variables was more than could be visible in the zoomed state, yet the dialog didn't add a slider and the next button was inaccessible.

**Comment by FadingSwordsman** [comment]
This was a problem in general with all modals. Now, when they're too large for the screen, they all limit themselves and display a scrollbar on the right side.

This affects both resizing the window and zooming in/out.
