### ISSUE TITLE
Need to standardize widget icons and their placement

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#369]
The new note text box is using a different scaling icon (triangle of 3 bars) than we are using for images.  Also the 'x' icon for deleting the box is on the right for the text, whereas the delete icon is on the left in the images. Since our users are coming more from the windows community, I think that the delete icon should be on the right.  This means swapping the delete and pin icons on the images and videos.  So Alex should modify the images and videos to swap the position, whereas Gabe should switch to using the scaling icon in the note box that the images and videos are using.

**Comment by alexsielicki** [comment]
I just did my part, swapped the position of close and pin icons in images and videos.

**Comment by alexsielicki** [comment]
@pjcross, I just noticed that the close icons themselves are inconsistent too. Which one should be standardize on?

**Comment by alexsielicki** [comment]
I'm now using the close and resize icons out of the same sprite as the text box is getting its close icon from.

**Comment by tshead2** [comment]
@alexsielicki, all else being equal, you should consider using the icons that come with bootstrap:  http://getbootstrap.com/components/#glyphicons
