### ISSUE TITLE
Text box updates are sometimes lost

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#370]
I've noticed that the text box updates are not always being captured.  Watching the bookmark in the URL line, I don't see it change with my typing.  I'd expect to see that each change generates an update to the bookmark to capture the new character being typed.

**Comment by lustrousgorilla** [comment]
Try pressing tab or clicking off of the box and let me know if you're still seeing the issue. If I update the bookmark per character typed, it will generate way too many requests, so it get's updated on the 'blur' event which fires whenever an input field loses focus.

**Comment by pjcross** [comment]
I can't really do much testing since slycat-dev is still gone. I don't think we can assume that the user will press tab or click off of the box.  I was trying to go back and forth between different models.  I think that when I lost an edit, I had clicked the back button on the browser or the refresh button.

**Comment by lustrousgorilla** [comment]
What do you think about using some sort of timer that starts counting down after they've stopped typing?

**Comment by pjcross** [comment]
That would be better, but how about this - since we can detect a hover, how about mouse movement outside of the text box?

**Comment by lustrousgorilla** [comment]
Ah, great idea.

**Comment by tshead2** [comment]
@lustrousgorilla, if / when you use a knockout observable for the text, you can turn on "rate limiting", then connect a change handler that updates the bookmark.
