### ISSUE TITLE
CCA point selection through click not working (Chrome and Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#388]
Clicking on points in the scatterplot no longer selects them.

**Comment by pjcross** [comment]
Also doesn't work in PI model

**Comment by alexsielicki** [comment]
Also, drag threshold is not working in Chrome. Meaning that drag starts right away, instead of after 3 pixels have been crossed as is intended. This is related to the same bug.

**Comment by alexsielicki** [comment]
Also affects PI+
