### ISSUE TITLE
Remote file browser can't back up a level

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#389]
The '..' line does not take me back up to the previous directory level, but this doesn't happen consistently.  The recurrent feature of when this happens is in the workdirs were the name is something like workdir.100.  I suspect that something about the '.' being in the name is key.  Originally I thought it was the leaves of the directory tree, but then I found that some leaves weren't a problem.

**Comment by tshead2** [comment]
Could be that it is just full of files and slow.  @pjcross : it would be good to have a specific path / host to test.

**Comment by pjcross** [comment]
That is not the problem, there are only 3 files in the directory.
