### ISSUE TITLE
Bookmark save reloads page

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#395]
When I create a bookmark using the 'Create' drop down menu, it reloads the page.  For a page with lots of images and points, this is slow and it is an annoying break in concentration to have everything flash and start to redraw.  Plus, this is not coordinated with the bookmark list on the side of the page.  The new bookmark is not included in the list after the reload, whereas if I create the bookmark using the save function in the bookmark list, the new bookmark is instantly visible and the page is not redrawn.  So we have two different paths through the code for this function that perform differently and are not synchronized.

**Comment by pjcross** [comment]
OK, this only does a reload when there is a title as part of the layout.

**Comment by pjcross** [comment]
Sorry.  Turns out the page reload is triggered by saving a bookmark using the drop down and then during the bookmark label entry, typing a return (enter) instead of clicking the save button.  It actually doesn't save it anywhere, so it is not coordination problem.  However, as the user, I have no way to know that my return aborted the bookmark creation until I leave the model and go back to the project page to see that my new bookmark is not in the list.

**Comment by FadingSwordsman** [comment]
When clicking enter, submit() was being called on the form, which reloads the page by default. This is now changed, and rerouted as though the user had clicked Save Bookmark.
