### ISSUE TITLE
Need to be able to delete or overwrite cached images/videos

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#400]
As we are experimenting with different video encoding approaches, I can only see my newly generated videos by changing the movie file name that I am using.  Even deleting the model does not work to remove the previously cached version.  I expect that cached files are found by hashing their names and paths, so that models don't even know which files are in the cache or not...I'm not sure what we can or should do about this, but I wanted to capture the behavior since I can imagine it could become a problem...

**Comment by pjcross** [comment]
Another example of this has emerged.  There's been some problems with disk hardware that has led to unsuccessful video retrieval.  This corrupted version of the file is the one that is cached, but now I have no way to remove it or replace it with a good version.  We need to expose a mechanism to the user that allows them to resolve a corrupted file in the cache.

**Comment by Mletter1** [comment]
Are we caching vids?

**Comment by pjcross** [comment]
A customer has requested this twice now...

**Comment by pjcross** [comment]
We can do this at the project level now. Although the customer would like to do this on a per model basis, that would end up increasing the size of the cache if images/videos that are shared between models were saved independently.  Maybe we could continue to share them, but if either model had its cache cleared, the shared copy would be removed.

**Comment by pjcross** [comment]
I'm not closing this until the project level cache deletion GUI gets another pass.

**Comment by pjcross** [comment]
Given our data-centric discussions, I don't think it worthwhile to hold this issue open any longer.
