### ISSUE TITLE
Movie positioning only possible if mouse in top/bottom borders of player

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#401]
I'm not sure whether to label this a bug or not, since the behavior may be a component of the video viewer.  However, for the user, it will appear that the dragging feature is broken if the user tries to move the frame by clicking anywhere within the movie viewer that is outside of the top or bottom edge.  Since images can be dragged by clicking anywhere within the frame, this will be confusing.

**Comment by Mletter1** [comment]
Is this still happening?

**Comment by pjcross** [comment]
No.
