### ISSUE TITLE
Shift click group selection for CCA input/output selection

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#403]
User request - user frequently has > 100 variables to be selecting during CCA ingestion.  Clicking each one either to transfer from the default input designation to output or to turn the variable off entirely is painfully slow.  User would like to do a shift click on the list to turn on/off groups of variables from the list.

We had previously discussed/designed a drag-and-drop interface that has been on hold for a long time.  I'm not sure if the shift-click proposal would be easier or harder to implement at this point, given all of the software changes since that branch was being developed.  I'd prefer the drag-and-drop interface in the long run, but if the shift-click option could be done sooner and fairly easily, then the shift-click option should be done as an intermediate solution.

**Comment by alexsielicki** [comment]
This is now finished as part of the revamped table ingestion UI.
