### ISSUE TITLE
Change model name from parameter-image model to parameter-space model

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#405]
Change the Create button drop down menu choice from 'New Remote Parameter Image Model' to 'New Remote Parameter Space Model'. Change the model icon in the model list from 'parameter-image model' to 'parameter-space-model'.  The reason for doing this now is that after meeting with our electrical customer, although he doesn't have any image data, he is trying to use CCA to do scatterplots (very painfully creating a new model for each one).  Since images are not required, the more generic parameter space model will provide him with the functionality he wants.  I think for adoption by the electrical community, now is the time to fix the name so it will make sense in their domain.

**Comment by Mletter1** [comment]
currently named "**New Remote Parameter Space Model**"

**Comment by Mletter1** [comment]
this issue would be solved with #420

**Comment by Mletter1** [comment]
This commit closes the issue 0b81add
