### ISSUE TITLE
Button release on slider lost (Firefox on Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#406]
I have not been able to trigger this bug in Chrome, though it seems to occur with some frequency in Firefox.  I cannot reliably reproduce the bug, but my working hypothesis is that it happens as follows:  I am moving the slider and although I haven't released the mouse button, I have paused in my movement.  There must be some time out on the movement because the table and scatterplot start to update to reflect the current threshold. During the update redraw I release the button, but it is missed.  Now as I move the mouse, the slider is following my movement.  If I wait until the next round of updates finishes, clicking the mouse will terminate the connection between the mouse and the slider.

**Comment by pjcross** [comment]
Customers are asking to have this fixed.

**Comment by alexsielicki** [comment]
Fixed by removing two instances where we were doing synchronous xmlhttprequests. The synchronous requests were preventing the mouseup event from firing if it occurred during part of the request on Firefox. These requests have been rewritten to be asynchronous and the problem seems to be gone.
