### ISSUE TITLE
Add point color selection drop down to CCA controls.

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#411]
Have the point color selection be a type-in box that will reduce the drop down list to the matching variables as the user types.

**Comment by pjcross** [comment]
Actually, this should exist in all of our drop down variable lists.

**Comment by alexsielicki** [comment]
So far I haven't been able to find anything that works with Bootstrap dropdowns, which are not <select> elements. This one seems most promising because even though it's jQuery, it can style itself to look like Bootstrap:
http://brianreavis.github.io/selectize.js/

**Comment by alexsielicki** [comment]
Looks like [Select2](https://select2.github.io/) can also easily be styled to look like bootstrap:
http://fk.github.io/select2-bootstrap-css/

**Comment by alexsielicki** [comment]
Point Color selection drop down is now in CCA. However, it does not incorporate the type-in feature mentioned earlier in these comments. @pjcross, is that still desired?
