### ISSUE TITLE
Color theme icon distorted in Chrome on Windows

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#425]
The background for the various themes is shorter than the legend it is behind, loosing the desired appearance of a mini-view.  This is true in both CCA and PS models.  It only appears in Chrome, not Firefox.
![image](https://cloud.githubusercontent.com/assets/4998608/7576354/f451d00c-f7f9-11e4-8af8-f64aa8d7ccab.png)

**Comment by alexsielicki** [comment]
This was an issue with Chrome and the "auto" setting for background-size. Changed to "100%" and that seems to have fixed it.
