### ISSUE TITLE
self._open_session used but no longer exists in parameter-image-scatterplot.js

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#428]
It seems that self._open_session has been moved or removed from parameter-image-scatterplot.js, but it's still used on line 1526. This might be causing a blank image callout with a spinner to be stuck on the scatterplot. 

![image001](https://cloud.githubusercontent.com/assets/66206/7640400/44c23cd2-fa40-11e4-8c60-fae7632c8c8f.png)

**Comment by alexsielicki** [comment]
This seems to have been introduced in commit 49837d785c2495df45c34df686b5e58cb030f7d9 which removed the _open_session function but left a call to it in the code that tries to create a session. Assigning to @FadingSwordsman since he's been assigned the double image issue which is in the same file and might be related.

**Comment by FadingSwordsman** [comment]
This was causing spinning images in some cases (When the agent died, specifically)
