### ISSUE TITLE
Timeseries Model Ingestion Wizard

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#436]
One of our users has asked for a simpler way to create time series models, that multiple push scripts are too complicated.

**Comment by srbdev** [comment]
Merged phase 1 to master: the only issue left is that the script fails if ran on more than 1 node at a time.

**Comment by srbdev** [comment]
I am leaving the ticket open until further testing has been made.

**Comment by srbdev** [comment]
-- Edit:
The following two components need to be added to the new Timeseries model ingestion wizard:

- a "Back" button
- a browser to select directories
