### ISSUE TITLE
missing log info

### ISSUE THREAD

**Issue by wlhunt** [sandialabs/slycat#437]
user id is occasionally missing from web server log, see example below

127.0.0.1 - joeuser [26/May/2015:11:54:53] "GET /users/- HTTP/1.1" 200 73 "https://slycat-test.sandia.gov/projects" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"
127.0.0.1 - - [26/May/2015:12:17:07] "GET /projects/5d527638e21b28232799325812345678 HTTP/1.1" 401 1065 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.6.3 (KHTML, like Gecko) Version/8.0.6 Safari/600.6.3"

**Comment by tshead2** [comment]
This is expected behavior, the client has logged-in yet, and the server is accurately reporting the information provided by the client.

**Comment by wlhunt** [comment]
What do you mean "logged-in yet". See full and non-sanitized log event provided in direct email.

**Comment by tshead2** [comment]
Fixed typo - *hasn't* logged-in yet.  The client hasn't supplied user credentials, so there is no username to log.
