### ISSUE TITLE
Slider Min-Max Entry Crossover

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#447]
If you reset the max to something lower, say 70 from an original of 319 and then you reset the min to something greater than the new max, say 300, the filter gets rid of all points (which is fine, given the nonsensical values).  I did this accidentally when I meant to type in 30.  So I correct it to 30 and the points are still all gone and the slider has lost its dots.  The only way I can get out of this is to reset both min and max.  I see that when I try to set the min to be greater than the data set max, I get an error message. However, shouldn't the test be against the current max instead of the data max?

**Comment by pjcross** [comment]
Similarly, I can set the max to less than the min so long as the value is inside the initial data range.

**Comment by alexsielicki** [comment]
This is now fixed. We now adjust high and low to always be in the range of max and min. However, we don't allow max or min to cross, even if the cross would put them within the initial range.
