### ISSUE TITLE
Create Model Dialogs Need Work

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#454]
There are several aspects of the current model creation process that could be improved:

1) The steps are shown as tabs that respond to mouse overs with a grey button-like affordance, but then are not actually clickable.  Either the user should be able to go forward and backward through the sequence by clicking, or the steps should not activate with a mouse over.  Also, having the button that you click in the lower right corner be called 'next' implies that maybe you should have a 'previous' as well, in case you want to change something in the previous tab.  If you can't go backwards, then 'OK' as the button label sets the expectation that you are done with the current pane.

2) The names of the tabs are misleading.  Create Model is not a good description for the naming step or the application of markings.  So 'Name Model' would make more sense.  Similarly, Select Type, would suggest that here I could pick CCA or Parameter Space.  Instead, I am pointing to the data, so 'Locate Data' is a better description.  

3) The 'Browse' tab inside what appears to be a type in box is odd. And if you click in the line next to the browse tab (to type in a path to your data), it still brings up a file browser.  When you have selected local, why not just automatically bring up the browser?

4) For the remote file browser, I like that it remembers where I was last time, but sometimes if I'm going to a new location that will require a large number of up directory clicks, then it would be faster to just type in a path.  I'd like the option of typing in the path (plus this would help when a particular disk is down and that was your last location on the cluster).

5) Users have asked about the meaning of the X for some of the files and thought it indicated a problem with the file.  I suspect it is intended to indicate which files can be ingested for the current file type selected (csv vs dakota tabular).  However, when I change the file type away from csv to dakota tabular, the csv files are still with an X and the dakota tabular files are not marked.  Since I think it would be tough to recognize dakota tabular files since they can be called anything and there is no consistent file extension used, I think we should not try to mark either type of file in the browser.

6) After the user has gone through the input/output column selection, they click on the button 'finish' and another pane comes up with a clickable link to go to the model.  I've watched users continually click on close (because throughout the rest of the process, that lower right corner button is used) and miss being able to use the link provided.  Why should they have to click on anything?  When they clicked on 'finish' in the previous pane, why didn't the system treat that as saying "take me to the new model"?  This last step is unnecessary and should be removed.

7) If you get to the model page before the model is done being prepared, it gives you a message, but then never updates once the model is ready.  Why should the user need to continually refresh the window to see if the model has completed?  Isn't there some way that we could do that for them?

**Comment by alexsielicki** [comment]
Finished 1, 2, 3, 5, 6.
Still working on 4, 7.

**Comment by alexsielicki** [comment]
Finished 4 and 7.
