### ISSUE TITLE
Remote directory browsing hangs

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#485]
When browsing during ingestion, I get a script stopped responding message when stepping to a new directory.  I believe this is due to long file lists being pulled (typically, lots of images).  As data is scaling, I expect that the number of files (both images and directories for each run) will make this approach to ingestion untenable.  I'm not sure how to handle the large number of directories, but we certainly should be filtering out media files (images of all kinds, videos, stl's) from our browser, since none of those will be candidate input files.

**Comment by tshead2** [comment]
@alexsielicki - you might try using the filtering parameters in POST Remote Browse to filter-out images before they get to the client.

**Comment by Mletter1** [comment]
This was likely a network error.
