### ISSUE TITLE
CCA parameter selection wizard checkbox rendering is wrong (Firefox 40.0.3 on Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#489]
In a data set with a long list of parameters, the checked boxes change from what is actually selected when the user scrolls or when the user's mouse hovers over the boxes.  Checks are either missing or faintly drawn in the wrong column.  Sometimes hovering erases or redraws the check boxes in their correct configurations.  Running with either missing checks or extra checks does not change the CCA parameters selected from what they would have been, had the checks been correctly represented in the wizard.

I notice that we are not using the newer checkbox selection (with shift-click multiple parameter selection here).  Rather than debugging this, I think we should be switching to the newer interface for consistency.  However, I see the same rendering problem with the new interface when inputting this same long parameter list (the dots come and go, and weird faint lines show up in the other column's circles).

![image](https://cloud.githubusercontent.com/assets/4998608/10028524/2f6cf312-612a-11e5-85a6-fe21b291546a.png)

**Comment by pjcross** [comment]
Inputting the same csv to the parameter space model wizard and using the shift-click mechanism, I'm seeing more weirdness:

![image](https://cloud.githubusercontent.com/assets/4998608/10028761/6c275b48-612b-11e5-8d7a-2d790a9a927f.png)

Plus, after selecting the input column for the group, it never completes the operation (hence the continual blue of the selected lines).

**Comment by Mletter1** [comment]
As a note this seems to work with FireFox ESR 38.3.0 on windows 7

**Comment by pjcross** [comment]
I can no longer produce the problem.
