### ISSUE TITLE
Replace POST Model Files API with New multipart-upload API

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#493]
Integrate new API into existing wizards.  From Tim's email of 9/21/2015:

New API documentation:

* http://slycat.readthedocs.org/en/latest/POST-Uploads.html
* http://slycat.readthedocs.org/en/latest/PUT-Upload-File-Part.html
* http://slycat.readthedocs.org/en/latest/POST-Upload-Finished.html
* http://slycat.readthedocs.org/en/latest/DELETE-Upload.html

Old API made obsolete by these changes:

* POST Model Files - still implemented in the server and client libraries, but removed from the documentation.

Example code:

* slycat/web-server/plugins/slycat-multipart-upload-demo

Running the example code:

* Configure your web server to load the slycat-multipart-upload-demo plugin.
* Point a browser to https://your-slycat-server/pages/multipart-upload-demo
* Use the file chooser button to point your browser to a copy of slycat/data/cars.csv (demo is hard-coded to work with this file).
* Click “Upload”.
* The plugin code splits the file into two pieces, uploads them separately to a CCA model, and finishes.
* Visit the new model to see that everything looks the way it should be.

**Comment by Mletter1** [comment]
note that these lines need to be added to the config.ini file

`upload-session-timeout: datetime.timedelta(minutes=15)`
`upload-store: "/var/lib/slycat/upload-store"`
