### ISSUE TITLE
Create warning for CCA ingestion for columns defaulted to neither

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#501]
During CCA ingestion of a table with many columns all set to zero, the ingestion wizard correctly defaulted those variables to the 'neither' category.  However, since there was no indication given that this was done to prevent an error, I changed them to outputs and ran CCA.  Of course it failed.  It took me awhile to realize why it failed.  It explained why the variables had not be initialized to be inputs.  I think that we can make the interface more informative and in addition to making those variables default to neither, we could color that variable's row in the ingestion GUI a pink color to alert the user that this variable has an issue.  Better still, would be some sort of note (possibly through hover?) that would state that any column where all the rows are identical cannot be included in the analysis.

**Comment by alexsielicki** [comment]
We are currently hiding string variables. Should we be consistent instead and follow a similar approach to those, meaning show them with an alert that the variable has an issue? @pjcross, what do you think?

**Comment by alexsielicki** [comment]
@pjcross, I'm finished with a first pass on this. It's only on the cca branch, as I want to show it to you for review before merging to master.
