### ISSUE TITLE
allow cherrypy log level to be set from config file

### ISSUE THREAD

**Issue by wlhunt** [sandialabs/slycat#504]

**Comment by Mletter1** [comment]
from wlhunt emial:

Here’s what I think needs to happen to control the cherrypy logging level.
 
Add line 60 to packages/slycat/web/server/engine.py:
 
```python
cherrypy.log.access_log.handlers[-1].setLevel(configuration["slycat-web-server"]["error-log-level"])
``` 
 
Add a web-server-config.ini line:
``` 
error-log-level: logging.DEBUG
``` 
 
The python logging levels are the typical:  CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET.
https://docs.python.org/2/library/logging.html#levels
 
I’m not sure what messages cherrypy emits on its own (outside the “cherrypy.log.error(“foo”) messages), so we should figure out a way to test this.

**Comment by Mletter1** [comment]
moved to #662
