### ISSUE TITLE
Update Timeseries GUI to match other models

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#510]
Color themes need to move to the new drop down style GUI.  It would also be useful to include the table download functionality, so that if users want to output table subsets based on selection or visibility, that they could do so.

**Comment by alexsielicki** [comment]
I'm also planning on adding the Outputs control as well as a control for selecting the waveform color variable to the new drop-down bar. @pjcross, let me know if you have any thoughts on this.
