### ISSUE TITLE
Sample timeseries creation script is broken

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#521]
When attempting to run the timeseries creation script, an error is generated complaining of a missing zmq module:

```python
[slycat@814f729c9d31 web-client]$ ./slycat-create-sample-timeseries-hdf5.py --help
Traceback (most recent call last):
  File "./slycat-create-sample-timeseries-hdf5.py", line 23, in <module>
    import IPython.parallel
  File "/home/slycat/install/conda/lib/python2.7/site-packages/IPython/parallel/__init__.py", line 21, in <module>
    import zmq
ImportError: No module named zmq
```

**Comment by alexsielicki** [comment]
```
pip install pyzmq
```
seems to solve this issue. We should probably update the image to include this module.

**Comment by alexsielicki** [comment]
@Mletter1 and @wlhunt, can you guys add pyzmq to the new image you'll be creating in the next few days? It's needed to generate sample timeseries data. Thanks!

**Comment by Mletter1** [comment]
added to docker image and dev/prod
