### ISSUE TITLE
CCA table sorting loses selected row (Firefox & Chrome on Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#528]
To create the problem, in a CCA model select a point, then sort by various columns in the table. The identity of the selected point will change depending on the column being sorted.

**Comment by pjcross** [comment]
I just realized that this is the same bug as #512

**Comment by pjcross** [comment]
It is also present in the Parameter Space model table.

**Comment by pjcross** [comment]
Could sorting order incorporate the index value to break ties?

**Comment by pjcross** [comment]
In the time series model table, even though columns have duplicate values, this doesn't happen.

**Comment by pjcross** [comment]
Additionally, looking at the same data set in CCA on the production server, it doesn't have this problem either.

**Comment by alexsielicki** [comment]
A version of this is also affecting PI models. Working on a fix now.

**Comment by alexsielicki** [comment]
Sorting should now be working well across all our models. Timeseries is still using old APIs but not exhibiting sorting problems, so I will open a separate issue for updating it.
