### ISSUE TITLE
No way to delete failed models

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#529]
I've had a problem creating a PI model and although the project shows the model as failed, when I click on the model link I get the Slycat eyes with the 'Page Not Found' message.  Ok, that makes sense since the model wasn't created, but without a model page, I have no Edit button to delete the failed model.  We need an additional way to enable this functionality that exists outside of the model page.

**Comment by pjcross** [comment]
I'm thinking that we should use the trashcan metaphor at the end of each model descriptor on the project page, similar to what we do with the bookmarks.

**Comment by pjcross** [comment]
You should work with Matt on this and have him do the server side piece.

**Comment by pjcross** [comment]
Add check boxes to do group operations.

**Comment by alexsielicki** [comment]
@Mletter1 is this still an issue or has it been fixed by some of your recent updates?

**Comment by alexsielicki** [comment]
This should now be fixed.
