### ISSUE TITLE
CSV table load errors for CCA and Parameter Space models

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#546]
This is only happens when loading a large file from your local machine.  The error message:

![image](https://cloud.githubusercontent.com/assets/4998608/11375250/681351d6-9297-11e5-8a5b-73c4be20d55b.png)

appears.  Clicking the OK, there is another below it, and another...As each one is removed by clicking OK, the black background starts to lighten to a dark gray and you can faintly see the variable selection window after getting rid of the 8th Alert.  For my test data, there were 10 Alerts in all.  Once they are all released, setting the variables works fine and the model can be completed.  However, the user may cancel out of the operation before that.

**Comment by Mletter1** [comment]
Test it now and see if you see the same errors
