### ISSUE TITLE
Add ipyparallel python package to developer docker image

### ISSUE THREAD

**Issue by srbdev** [sandialabs/slycat#552]
The Python package "ipyparallel" should be added to the development docker image. It is used for the IPython.parallel functionality, which is used in several push scripts.

**Comment by srbdev** [comment]
@Mletter1 I've added you to the ticket since you were the last one to build the image. If you have time to show me how to do, I'd gladly take the ticket from your hands.

**Comment by Mletter1** [comment]
also #521

**Comment by Mletter1** [comment]
added to docker build
