### ISSUE TITLE
Improve sign in and sign out process

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#560]
Ideas for improving the sign in and sign out process:

1. When deep-linking into Slycat (e.g., pasting a link directly to a model), the sign in page should come up and after signing it, the user should be redirected to the link they originally pasted. Currently the original link is lost and the user just ends up on the project listing.
2. Signing out should just bring up the sign in page instead of the "You have been signed out" page. This page seems extraneous now that we have a dedicated sign in page instead of the browser popup.

**Comment by alexsielicki** [comment]
Another idea is to keep the location from which the user logged out and bring them back to the same location when they log back in. This should happen both when the user manually logs out and when they are logged out automatically due to timeout. For example:
1. User is on a CCA model called "Cars"
2. User clicks "Sign Out"
3. System signs them out and presents them with the Sign In page
4. User signs back in with their username and password
5. System redirects them to the "Cars" CCA model right after sign in.

And:
1. User is on a CCA model called "Cars"
2. User leaves for the night. 
3. After some timeout period, system automatically signs them out and redirects them to the Sign In page
4. User returns in the morning and signs back in with their username and password
5. System redirects them to the "Cars" CCA model right after sign in

One way I've seen this handled is with URL GET parameters, like so:
https://192.168.99.100/login/slycat-login.html?from=https://192.168.99.100/models/2a89fa310d2647e5bc268028379b430b?bid=12e41568da4b178b66e7da75650b6c31

**Comment by Mletter1** [comment]
I believe we have accomplished everything we have set out to do with this enhancement
