### ISSUE TITLE
Time out on login doesn't go to login page

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#561]
I left myself logged in overnight.  In the morning my session was expired.  My webpage was still visible (I was in a parameter image model).  As I hovered over one of the points, the Remote Login popup appeared.  I logged in, but since my session was expired, the remote login was not what was really needed.  The popup display the error message - "Error opening remote session: Temporary Redirect". This really didn't tell me as a user that the session was expired, nor did it redirect me to the top level login page.  As a user I'd be stuck at this point since using the popup to login again wouldn't do anything.  Instead of the popup, the user should be redirected to the login page once they try to interact with a model after the session has expired.

I put this into a separate issue, even though it is related to issue #560, because this is really a bug.

**Comment by Mletter1** [comment]
I think this should be done with the 

```html
<element onload=timeoutScript()> 
```

maybe something like

```html
<body onload="setTimeout('window.location = \'server_root\/\';', (session_max-(current_time-session_start)));">
```
