### ISSUE TITLE
Bookmark corrupted during image pin (Windows 7, Firefox and Chrome)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#565]
The bug is produced by hovering over a point to retrieve an image and clicking the pin icon.  It is NOT a result of rubberband selection followed by using the pin option in the Selection Action menu.  The bookmark created has only the height and width, but is missing the URI for the image.  This visually manifests in the inability to redraw the image, so the line connecting the image to the source point in the scatterplot is shifted and if the page is refreshed, the pinned image is lost and a URI not found error is generated.

**Comment by pjcross** [comment]
Looking at the bookmarks produced, if you move the image before pinning, the image is included normally in the bookmark from the move, but pinning it adds a second image to the bookmark that is missing the image URI (even though you are interacting with the same image all along).  

If you pin the image immediately without moving it, then the bookmark has only the broken image reference.  If you then hover over another point to retrieve a second image, the first pinned image will disappear, though the new image from the hover will be displayed normally.  Pinning the new image does not add a second image to the bookmark.  It still shows only the single corrupted one with no URI.  Although the image appears to be pinned and smaller, moving it causes the image to resize to its larger original scale.  The move causes a second image to be added to the bookmark, this time with the URI.  Pinning it again will make it smaller, but any movement will resize it larger.

**Comment by pjcross** [comment]
Additional impacts of this bug: once the bookmark is corrupted, changing the size of the window results in the loss of the legend and incorrect placement of pinned images.

**Comment by alexsielicki** [comment]
Even after fixing the bookmark corruption, I'm still seeing the "moving image causes it to resize" problem, but only intermittently. That makes it very difficult to track down and fix.
