### ISSUE TITLE
Multiple copies of the same model listed (Windows 7, Firefox only)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#566]
The model times are identical on the multiple copies.  The latest bookmark is shared among all the versions, so they behave as a single model (changing state in one will change state in all of them).  They do not appear replicated in Chrome.  The problem appears to be the latest version of Firefox.  I just upgraded from version 38.5.2 to version 43.0.4 and the problem appeared immediately afterwards.

**Comment by pjcross** [comment]
Fixed.

**Comment by alexsielicki** [comment]
Just documenting that this seems to be caused by Firebug or Firefox Dev Tools being open. Even then, it's intermittent.
