### ISSUE TITLE
Missing values in numeric columns force string-type on input

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#573]
One of our users requested that Slycat handle numeric columns with missing data by treating the column as real valued instead of a text column.  He was working in the Parameter Space model.  This becomes an issue when the user wants to do filtering on that variable or color-code the points that do have values.  He didn't want to add dummy values like zero, since his data might naturally have those values.  I suggested that he fill all of the blanks in the csv with Nans.  This will enable him to filter and color-code those points that have values.  I can see that the same situation would also cause issues with CCA since the entire column would be unavailable for analysis, rather than just removing the row with the missing value (our CCA behavior with Nans).  Although we can push the issue back into a preprocessing step for the user, I think it would make more sense if we provided an avenue to take care of this while parsing the table during ingestion.  Maybe we could offer a checkbox in the wizard to insert Nans into blanks?  That way if the user was looking for Nans in the original data, they could turn it off.  But for most cases, we would just automatically insert Nans, which would provide the desired behavior in the models.

**Comment by Mletter1** [comment]
need to add this to .dat
