### ISSUE TITLE
User must redo data ingestion to change variable types/attributes

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#574]
One of our users asked that instead of forcing him to recreate a model in order to change a variable type from input to output, or to treat the variable as categorical in the filters, that he be allowed to just edit the designations using the yellow edit button within the model.  The button would retrieve the wizard page that selects inputs/outputs/neither and categorical.

**Comment by alexsielicki** [comment]
While working on this I realize that we need to handle situations where already filtered variables change from categorical to continuous, and vice versa.

**Comment by alexsielicki** [comment]
We should probably test filtering for editable variables. Not sure if we ever considered this use case.
