### ISSUE TITLE
Models drawn twice (Chrome and Firefox on Windows)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#582]
I see this intermittently, but the way to reliably produce it is to create a new model and load it.  The model will draw, erase, and redraw the very first time you load it.  Reloading after that, I don't see this behavior, so maybe it is only for models that aren't cached yet.  I've definitely seen it in CCA and Parameter Image models.  Parameter space loaded so quickly that I'm not sure, though I believe it happened there as well.  I suspect that it happens in all of them

**Comment by Mletter1** [comment]
we fixed this with a javascript logic change on window reload
