### ISSUE TITLE
Halting retrieval of model list (Chrome on Windows and OS X)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#583]
For the Demos project on the production server, the model list loads in fits and starts.  This creates issues when I start to click on a model and suddenly another few models in the project are added to the list, causing me to select the wrong model.  I see it only in Chrome, both on my desktop (Windows) and my laptop (OSX) and I've seen it repeatedly over at least a week or more.  Since it doesn't happen on Firefox (and I've tested it in between seeing it on Chrome, where the halting load occurs both betore and after reloading the same model list on Firefox), I doubt that it is a network issue.

**Comment by Mletter1** [comment]
https://wiki.apache.org/couchdb/Compaction could potentially clear some of this up

**Comment by Mletter1** [comment]
This only happens on re-start of the web server and as we clean other bugs is becoming less of an issue
