### ISSUE TITLE
set utf8 encoding

### ISSUE THREAD

**Issue by Mletter1** [sandialabs/slycat#590]

**Comment by jecompton** [comment]
Need more discussion to come to a consensus on whether to put this header at the top of all our .py files:

# -*- coding: utf-8 -*-

As best as I can tell, this is the best practice, but devs would need to be careful to do this (through template or discipline).

**Comment by jecompton** [comment]
Also need to try throwing different chars in the source in my container and see if this line actually does resolve it or if there is a different problem.

**Comment by Mletter1** [comment]
this was a python 2 thing would need to investigate if this is useful for python 3
