### ISSUE TITLE
Model Name Component

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#593]
Make a component out of our current model name tab (name, description, marking type).

**Comment by pjcross** [comment]
Not sure if I should put this in a separate issue...but for this tab in the CCA model wizard, we were seeing two types of errors: issues with sizing the dialog (this was in Safari on OSX) and being kicked out of the model creation wizard when hitting enter while the cursor was in the name field.

**Comment by alexsielicki** [comment]
Turns out this is already a component. I will work on the resizing and enter keypress issues.

**Comment by pjcross** [comment]
This was fixed long ago and should have been closed.
