### ISSUE TITLE
SLURM interface improvements

### ISSUE THREAD

**Issue by srbdev** [sandialabs/slycat#595]
The following changes will need to be made to the SLURM interface:
    - remove submit, cancel and clear output buttons
    - remove agent function dropdown and include function as input
    - add mechanism to monitor/control submitted jobs from the model page

**Comment by srbdev** [comment]
The following components need to be added to the SLURM interface to improve its functionality:

- add functionality to use a .slycatrc file under a user's home directory for default values
- batch files should be saved under /tmp
- disposable working files should be saved under /tmp
- persistent generated files (i.e. distance matrices, hdf5 files) should be saved under a user's defined folder
- keep one SLURM .out file under the /home directory that is overwritten for each jobs

**Comment by srbdev** [comment]
It looks like this was closed by mistake during commit 64877f4.

**Comment by Mletter1** [comment]
for the most part this is fixed everything else is new features or bugs
