### ISSUE TITLE
Hover picking points behind video for image retrieval (Chrome on Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#600]
As I am operating the controls to start and stop a video, hovering over the play button is causing the image for a point hidden under the video to be launched.

**Comment by alexsielicki** [comment]
Verified that it happens in FF too, at least under OSX.

**Comment by alexsielicki** [comment]
Verified that it happens for images too, not just videos.

**Comment by alexsielicki** [comment]
This also affected PI model and the fix was easy to apply there so I went ahead and did that.
