### ISSUE TITLE
Some table column headers not displayed on hover (Firefox only, Windows 7)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#603]
When hovering over column headers that are too long to fully display, a subset of them will not popup with the full title, no matter how long the hover lasts or where in the cell the mouse pointer is located.

**Comment by pjcross** [comment]
This seems to happen only in Firefox, maybe only in Windows, and just for columns that are slightly too long. If sized down further, the hover comes back.

**Comment by alexsielicki** [comment]
We are having problems reproducing this, so closing for now and will address later if it keeps happening. The fix would be in slick.autotooltips.js
