### ISSUE TITLE
Change time from UTC to local

### ISSUE THREAD

**Issue by srbdev** [sandialabs/slycat#606]
Timestamps used for the model creation and other use UTC instead of locale. Search for "datetime.datetime.utcnow()" to locate all the places that need to be modified.

**Comment by Mletter1** [comment]
after discussion we will move this to js side code

**Comment by Mletter1** [comment]
maybe something like 

```javascript
var date = new Date('6/29/2011 4:52:48 PM UTC');
date.toString() // "Wed Jun 29 2011 09:52:48 GMT-0700 (PDT)"
```

http://stackoverflow.com/questions/6525538/convert-utc-date-time-to-local-date-time-using-javascript
