### ISSUE TITLE
Speedup Timeseries Model

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#613]
We need to speed up our timeseries models to improve scalability.  Matt suggested removing all the text for the file URLs from the table, since they don't contribute to model.  Another thing that he noted was that we're pulling metadata first thing and that everything else is stalled waiting on its retrieval.

**Comment by Mletter1** [comment]
This commit e4bbe99 speeds up server to client data transfer by multiple factors of 10

**Comment by alexsielicki** [comment]
My part in this is finished. Reassigning to @Mletter1 in case he still has work he wants to do on this.

**Comment by Mletter1** [comment]
time-series is now sped up
