### ISSUE TITLE
Parameter Image ingestion fails (Firefox & Chrome on Windows 7 and OSX)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#614]
At the point where the job should be launched, it fails with the following error message:
![image](https://cloud.githubusercontent.com/assets/4998608/14191282/42062fbe-f754-11e5-9d98-fd6d4f30cb1d.png)

**Comment by srbdev** [comment]
This has been ruled out to having the user's home directory being full when trying to submit a job via the SLURM interface.
