### ISSUE TITLE
Long list of variables cuts off bottom choices in Waveform Color drop down

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#619]
The variable list doesn't get a scroll bar when the list length exceeds the available space in the window.

**Comment by alexsielicki** [comment]
Problem is also that it displays under the table instead of over it.

**Comment by alexsielicki** [comment]
Good news is that this only affects timeseries. The other models have both scrollbars and display the menus over the table.

**Comment by alexsielicki** [comment]
Still need to address the issue where the menu displays under the table, but this requires restructuring the model html so I want to wait until after the milestone.
