### ISSUE TITLE
Save ssh session with slycat sessions

### ISSUE THREAD

**Issue by Mletter1** [sandialabs/slycat#633]
we need to save ssh session with slycat sessions so we don't have to keep logging in to images or videos

**Comment by alexsielicki** [comment]
@Mletter1 I'm seeing a problem where login breaks when the server is restarted. Specifically, I open a PS model, hover over a point, log in, everything is working. I restart the server, then hover over a point, get a login dialog, log in, and keep getting the login dialog again and again. Any ideas?

**Comment by Mletter1** [comment]
@alexsielicki Commit  197c147 should fix the server restart and login issue

**Comment by alexsielicki** [comment]
@Mletter1 I'm seeing another problem. I can't upload a file without a session id. I think the PUT Upload File Part API needs to be updated to take a hostname instead of session id:
http://slycat.readthedocs.io/en/latest/PUT-Upload-File-Part.html

**Comment by Mletter1** [comment]
@alexsielicki The session for out upload file part is no the same thing as the ssh sessions. This is a file session that is deleted once the file is uploaded. That way when you upload places to a file the have a session to upload to

**Comment by pjcross** [comment]
Be sure to rename the variable from sid to something different to avoid this confusion in the future.

**Comment by Mletter1** [comment]
@jaxon-gittinger  we need to update checksid to use hostname and become a get call, similar to commit  1c86615

```python
 dispatcher.connect("post-checksid", "/remotes/checksid", slycat.web.server.handlers.post_checksid, conditions={ "method": ["POST"] })
```
