### ISSUE TITLE
Remove media from waveform color list

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#637]
Currently, the variable list for coloring the waveforms includes video, image, and time series csv files.  Selecting any one of these for color-coding makes no sense, so they should be filtered out before the list is created.

**Comment by alexsielicki** [comment]
Reassigning to @srbdev since the rest of this work is in the timeseries wizard and scripts. They need to be updated to determine media columns upon ingestion and save them under the "image-columns" or "media-columns" attribute.
