### ISSUE TITLE
Add toggel for hover over images and videos

### ISSUE THREAD

**Issue by Mletter1** [sandialabs/slycat#640]
Allow the user to control the hover -> display behavior.  In “exploration mode” the current behavior is followed in “presentation mode” the user controls when media is displayed (for example right-click -> select from a set of available media for that point)

**Comment by pjcross** [comment]
I think the easiest way to address this is to make the first Media selection choice to be "none".  That way the default behavior is not to pull images/videos until the user signals their desire for image/video retrieval by selecting a media variable.

**Comment by alexsielicki** [comment]
I added the "None" choice as the first option in the "Media Set" drop down. Also, I'm disabling the "Pin" choice in the "Selection Action" dropdown when "Media Set" is set to "None".

**Comment by alexsielicki** [comment]
Defaulting "Media Set" to "None" upon model load when no bookmark is present with Media Set saved in it. @pjcross, is this correct behavior? Or would you prefer the default to be the first available media set?

**Comment by pjcross** [comment]
Yes.  Defaulting to "None" is the correct behavior when no bookmark is present.
