### ISSUE TITLE
Add font controls to models

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#642]
A user has asked for the ability to change font size in the models:  "The default color/fonts are difficult to see in conference rooms with older flat screen TVs.  I would like to have larger fonts on white background.  Are there controls to customize the scatter plots?"

**Comment by Mletter1** [comment]
control plus?

**Comment by alexsielicki** [comment]
This is now finished for Parameter Space model on the axes branch. Still need to apply this to our other models.

**Comment by Mletter1** [comment]
I think we should close this for now. what do you think @alexsielicki?

**Comment by alextikr** [comment]
Sounds good to me, @Mletter1

**Comment by alexsielicki** [comment]
Sounds good to me @Mletter1, closing and we can reopen if the need comes up for other models
