### ISSUE TITLE
Allow project information to be edited at the model level

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#643]
A user was trying to add a new member to a project using the edit button within a model and was confused that they couldn't find it.  The user didn't recognize that they have different editing capabilities depending on whether they are at the project level or at the model level.  I can't think of any reason to force the user to leave a model and return to the project level in order to add someone to the project.  We should add 'Edit Project' to the Edit button within the model level.

**Comment by Mletter1** [comment]
help text or a link might be better

**Comment by Mletter1** [comment]
added with f1b7910
