### ISSUE TITLE
Add MD5 hash for files on remote servers

### ISSUE THREAD

**Issue by srbdev** [sandialabs/slycat#649]
Compute the MD5 hash for files that are generated on the remote servers and which Slycat will need to ingest to ensure the integrity of the data computed remotely.

**Comment by srbdev** [comment]
After some discussion, it was suggested that the data generated on the remote systems should be bundled into a tarball, shipped to the Slycat server once and the model computed directly from the Slycat server hard drive. Using this approach should help with performance and would allow the hashing function to not impact performance as much as trying to hash every single file, one at a time.

**Comment by Mletter1** [comment]
re-visit later
