### ISSUE TITLE
Make SLURM module and agent HPC agnostic

### ISSUE THREAD

**Issue by srbdev** [sandialabs/slycat#655]
The SLURM needs to be refactored in order to implement remote_computation_interface.py interface and the code to be abstracted out of Slycat plugins and core codebase.

**Comment by Mletter1** [comment]
After an in dept review of the Slurm code this is the plan.

An agent will now reflect the HPC system it is running on

- It will be written to follow an interface that will be our mapped connection from the server to a generic HPC
- all code written will reflect the server it was written for and follow the interface for it.

**Comment by Mletter1** [comment]
done interface is made
