### ISSUE TITLE
Timeseries Push Scripts - First Model View Has Error Message

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#665]
Even though the push script has correctly generated the model, the very first time you view it, you get the "OOPS, ..." error message about being unable to read the data.  In fact, I got two of those messages stacked on top of one another.  However, before I could copy down the text of the error message, the popups disappeared and the model was drawn.  All subsequent views of the model do not exhibit this behavior.  Nor do I see this with ingestion using the wizard.

**Comment by Mletter1** [comment]
are we still seeing this error?

**Comment by Mletter1** [comment]
or was it fixed with the other updates we have been doing?

**Comment by pjcross** [comment]
I am no longer seeing this.
