### ISSUE TITLE
Improve time series wizard UI

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#666]

**Comment by alexsielicki** [comment]
Quick note to document the current implementation of the time widget. If the user left it last with "Use recommended values" checked, it will not restore time values. However, if use left "Use recommended values" unchecked, it will restore the last used time values. @pjcross, let me know if this sounds good, it's a little different than what we discusses.

**Comment by alexsielicki** [comment]
@pjcross, what do you think about not allowing users to cancel their timeseries models on the last tab (Name Model) of the wizard? When they are on the last tab, the job has already been submitted to the remote agent, so cancelling the model would delete it and the agent would have to deal with this condition of a missing model. Let me know if you'd like users to be able to cancel on the last screen because it's currently coded to not allow cancel and back buttons on that last step.

**Comment by alexsielicki** [comment]
@pjcross, does Cluster Sample Count need to be an integer?

**Comment by pjcross** [comment]
@alexsielicki In response to your questions:
- Use recommended values:  I'm assuming here that we are talking about the automatic guess by Slycat about how much time the analysis will require (to put into the queue submission).  I'm thinking that the text, "Use recommended values" might be unclear.  Could we say, "Estimate run time"?  Then if this is checked, we provide the time, and if it isn't checked, we restore the last used time values (essentially the behavior you described, but with a different label).
- Canceling model on the last tab of the wizard: I actually think that we do need to provide a way to cancel after the job is submitted.  Perhaps the user realizes they made a mistake in the setup at this point, or they change their mind about creating the model.  It is a waste of computational resources if they have no way to abort the job.  Plus, if they then go through the wizard a second time to fix the issue, their new job is competing in the queue with the previous job that they already know they don't want.
- Cluster Sample Count: I'm assuming here that we are talking about the parameter that sets the number of bins for sampling the timeseries.  Once again, I think we need a more descriptive label, perhaps "Time series bin count"?  Because it is a bin count, it must be an integer.
