### ISSUE TITLE
Add flag to file browser for limited list return

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#671]
Returning the entire /usr/ directory takes too long on some systems. Let's figure out a way to limit the return so the file browser only shows first x rows, then as user scrolls, more rows become visible.

**Comment by Mletter1** [comment]
on the linux side of things I do not think that this is possible without still pulling the full list on linux

**Comment by Mletter1** [comment]
because of the previous comment I think we have to scrap this as no matter what we do linux will always ask for the full list and this is what slows down the return not the data itself
