### ISSUE TITLE
Color waveforms by strings

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#684]
In the parameter space model, we color points by string values (categorical variables).  We need to be able to color the wave forms in the same way.

**Comment by pjcross** [comment]
I just realized that this is #522

**Comment by alexsielicki** [comment]
@Mletter1, it seems that our "GET Model Arrayset Metadata" API call does not work on Timeseries models:
https://slycat.readthedocs.io/en/latest/GET-Model-Arrayset-Metadata.html

I need this to retrieve unique values of string variables so I can color code by them. Can you look into this and let know what's going on? Thanks!

**Comment by alexsielicki** [comment]
@Mletter1, never mind, I was just asking for the wrong attribute (data-table instead of inputs).
