### ISSUE TITLE
Add viewer for colored 3D surface models

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#690]

**Comment by Mletter1** [comment]
we should look at three.js

**Comment by pjcross** [comment]
User has requested that VRML and X3D media types as inputs

**Comment by pjcross** [comment]
We won't be doing VRML, since that is a dying format.  Integrate X3D viewer into Parameter Space model.

**Comment by pjcross** [comment]
Done using vtp as our mesh file format, which is more versatile that X3D because we can include more than one variable in the file.  The user can then interactively switch between variables for color-coding the surface.
