### ISSUE TITLE
Add PFLOTRAN wizard for time series models

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#696]
A customer uses TecPlot format to save time series output.  They would like to be able read this format natively within the wizard.

**Comment by Mletter1** [comment]
@pjcross do we want to still do this?

**Comment by pjcross** [comment]
I haven't gotten any recent requests, but I wouldn't close the feature request.

**Comment by pjcross** [comment]
The cost vs. benefit is too low to implement this feature.  I'm closing it.
