### ISSUE TITLE
Images revert to original size when moved (windows/firefox)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#698]
This doesn't happen all of the time.  I've been trying to find a pattern of when it happens and when it doesn't.  I can pretty reliably trigger it by pulling an image, moving it, pulling a second image, resizing it, moving the first image, then moving the second image (which now returns to its original size as I move it).  For awhile I thought it was when there was more than one image, but I've gotten it to trigger with only one image visible.  Then I thought it was images that were the 2nd or greater in display order, but once again, I've been able to violate that and have up to 3 images behave themselves (even when they were initially resizing themselves, they stopped and I don't know why).

**Comment by alexsielicki** [comment]
The pattern that triggers it is:
- Hover over a point to preview an image.
- Pin the image
- Close the image
- Hover over the same point to preview the same image
- Pin the same image again
- Click the image and it jumps back to it's preview size
