### ISSUE TITLE
Labels in Timeseries Parameter Tab need work

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#700]
In the time series wizard, the meaning of the labels for parameters in the Timeseries Parameter tab are not very descriptive.  As I'm writing the user manual, it has taken me some digging to recover what was being done and what these parameter values signify.  Since not everyone will read the manual, I want to make it explicit in the interface.

In particular, I want to change 'Cluster Sample Type' to 'Resampling Algorithm'.  The two choices in the associated dropdown are currently uniform-paa and uniform-pla.  These need to be more clearly spelled out to be 'uniform piecewise aggregate approximation' and 'uniform piecewise linear approximation'.  If these strings are too long for the field, then perhaps we could see the expanded form during hover.

I want to change 'Cluster Type' to 'Cluster Linkage Measure'.  Then for each of the choices: 'single: Nearest Point Algorithm', 'complete: Farthest Point Algorithm', 'average: Unweighted Pair Group Method with Arithmetic Mean (UPGMA) Algorithm', and 'weighted: Weighted Pair Group Method with Arithmetic Mean (WPGMA) Algorithm'.  If the last two are too long, perhaps we could use the abbreviations UPGMA and WPGMA in the selection list.

Additionally, I see that scipy provides a bunch of alternative metrics besides Euclidean distance.  Could we add a couple of the more well-known ones like 'cosine' or 'correlation'?  It currently feels silly to include a field for the 'Cluster Metric' selection and then provide no choices.  Here's the reference for all the distance metric choices in scipy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html

Most of this is just a simple relabeling of the fields, but there would be a small change to  slycat/web-client/slycat-create-timeseries-model-from-hdf5.py to add "cosine" and "correlation" to the list of --cluster-metric choices.

**Comment by alexsielicki** [comment]
@pjcross, I completed the relabeling. If you still want to add "cosine" and "correlation" as additional cluster-metric choices, please let @Mletter1 know he needs to make the back end change. Once he's done with that, I will add the drop-down choices. Otherwise, just close this issue. Thanks!

**Comment by pjcross** [comment]
I'm closing it.  If we want to expand our functionality later, I'll make a new issue for it.
