### ISSUE TITLE
Select HDF5 Directory - Need feedback when to stop

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#701]
When I navigate to the hdf5 directory, do I stop when I am at the level where I see the directory (a single click doesn't highlight it to select it) or do I need to go down a level into the hdf5 directory so that I can see the hdf5 file list?  I think that it is the latter, but I can't tell until I finish running since both options allow me to continue to the next screen of the wizard.  The first option leads to a failure, the 2nd option works.

**Comment by alexsielicki** [comment]
We decided to change the text above the directory chooser to:
"Please open the directory containing your HDF5 files"

Also, we will add a pop-up after the user clicks Continue:
Please confirm this is the directory containing your HDF5 files:
<directory path>

[Yes] [No]

Clicking Yes will continue to next screen, clicking No will simply close the confirmation dialog and leave the user on the HDF5 directory screen.
