### ISSUE TITLE
Xyce input table file wrong - Time series wizard

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#702]
No matter which dakota_tabular.dat file I enter into the wizard, it always uses the same one.  I believe that the problem is in the interaction with the slycatrc file.  There is key called persistent-output that links to an old hdf5 directory I made that would match the outputs I am seeing.

**Comment by Mletter1** [comment]
@pjcross is this still an issue? I think we may have fixed this

**Comment by pjcross** [comment]
Not seeing a problem now, so I'm closing it.
