### ISSUE TITLE
Chrome websocket connection fails in Single sign-on (Mac & Windows)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#704]
Although you can see the Slycat header in the projects page, none of the projects are visible.  The websocket connection is failing.  Matt has tracked it to Apache.

**Comment by wlhunt** [comment]
Apache correctly handled a websocket rewrite backreference for firefox but not for chrome/safari. Fixed by using apache env var for uri instead of backreference.

**Comment by pjcross** [comment]
Intermittently still fails to populate project and model lists.  Impacts breadcrumb list.  Draws models, but the breadcrumb is replaced by Slycat.  Clicking on Slycat fails to redraw the project list, though the URL is correct.  Refresh will temporarily fix things.

**Comment by Mletter1** [comment]
#732 closes this issue
