### ISSUE TITLE
Getting unique column values sometimes throws error

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#709]
Asking for unique column values using the get_model_arrayset_metadata API sometimes throws an error for string columns. This might be cache related. Seems to be due to sometimes part of the result coming back as a list object instead of the anticipated numpy.ndarray object. I added a bandaid for now, but this should be properly fixed, probably by @Mletter1. Here's the temp fix I added on the bugfix branch (where I'm working on timeseries coloring by string variable):
bbb61cd69e01ee19c9277f6e3675f398458f404e

**Comment by Mletter1** [comment]
change to isinstance()
