### ISSUE TITLE
Multiple File Select in Local Browser

### ISSUE THREAD

**Issue by smartin71** [sandialabs/slycat#710]
Please add multiple file select option in slycat-local-browser.  Thanks.

**Comment by alexsielicki** [comment]
@smartin71, remind me again, is this for DAC or the new video model?

**Comment by alexsielicki** [comment]
@smartin71, this is now ready for you to use. Just add `multiple:true` as a parameter to your slycat-local-browser. For example:
`<slycat-local-browser params="selection:browser.selection, multiple:true"></slycat-local-browser>
`

Also, I added a comment to the code describing the new option: b3f155c :)
