### ISSUE TITLE
Add external demo website based on public docker image

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#718]

**Comment by Mletter1** [comment]
once #740 is done we will be able to complete this

**Comment by Mletter1** [comment]
alright our image is ready see https://hub.docker.com/r/slycat/slycat-developer/

**Comment by alexsielicki** [comment]
I just finished putting an external demo slycat site:
https://myslycat.com
(slycat.com was already taken)

It's currently still showing a certificate warning and will keep doing that until my new certificate arrives. In the meantime, feel free to play around and let me know if you find any problems.

**Comment by alexsielicki** [comment]
FYI, Slycat needs about 1GB of RAM. I couldn't get it to work on a 500MB VM. Got the following error on CouchDB startup:

ll_alloc: Cannot allocate 494927872 bytes of memory (of type "port_tab"). Aborted (core dumped)

Looks like Couch wants 500MB memory just for itself.

**Comment by alexsielicki** [comment]
The new certificate is now installed and seems to be working. You should no longer be getting warnings from the browser.

**Comment by pjcross** [comment]
The example CCA model for TAIS that we provide needs to be changed to make the inputs be ajo, bjo, njo, and beta.  The outputs need to be ndrf_last and ndhr_last.

**Comment by pjcross** [comment]
We should designate the above variables as input/output columns in the Parameter Space model as well.  The color-coding helps to understand the data, which will be unfamiliar to users.  Also I'd like to have the description for the Parameter Space TAIS model be as follows:

Taylor Anvil Impact Scenario (TAIS) SIERRA/SM CATALYST DAKOTA.
SIERRA/SM CATALYST DAKOTA ENSEMBLE ANALYSIS of an Oxygen Free High Conductivity (OFHC) Copper Cylinder of Length 2.54 cm and Diameter 0.762 cm with initial velocity of 190 m/sec impacts a rigid wall. A Johnson-Cook inelastic constitutive law was used with the finite element analysis code, SIERRA/SM (i.e., "presto"), to numerically predict the response and final deformed shape. The Dakota parameter sensitivity study considered four parameters of the Johnson-Cook constitutive law, AJO, BJO, NJO, and BETA (the fraction of plastic work converted to heat).

**Comment by pjcross** [comment]
In the cars Parameter Space example, inputs are cylinders, displacement, weight, year, and origin.  Outputs are MPG, Horsepower, and Acceleration.  Model is neither since it is really just a label.  Since cylinders, year and origin have small, fixed numbers of value choices, I want to make them be categorical so that we have an example of buttons in the filtering.

**Comment by pjcross** [comment]
I tried creating a bookmark for the cars Parameter Space model, but it darkened the screen and never brought up the dialog.

**Comment by pjcross** [comment]
We should either remove the help button ("?") or add a real email address (currently it goes to nobody@example.com).

**Comment by alexsielicki** [comment]
Which email should we use for the help button?

**Comment by pjcross** [comment]
Why don’t you put my email.  The slycat-help address is limited to Sandia, so we can’t use it.

Pat

**Comment by alexsielicki** [comment]
Creating bookmarks and renaming models work for me from home on Safari and Firefox on macOS. Info works as well. Perhaps it's a Windows issue or Sandia network?

**Comment by alexsielicki** [comment]
I swapped in your email address, @pjcross 

I'm using mine for the error emails.

**Comment by Mletter1** [comment]
907b99a as of this commit we have a new docker image, we just need to add some example models to it then we can put it up on the website and commit the image to dockerhub as well
