### ISSUE TITLE
Add capability to include NULL valued runs in filtered scatterplot

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#730]
One of our users would like to integrate experimental data and be able to filter on it, but some of the parameters are NULL.  He would like to see the filtered values combined with the NULL values.  Currently, if you filter on a variable that includes NULLs, all the NULLs are removed from the plot.

**Comment by Mletter1** [comment]
Commit 6aadc1b adds or(a1 == nan) logic to hql
