### ISSUE TITLE
Updates to Model Pages

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#744]
I suspect this is a result of removing the websockets.  When I edit (as in using the edit button) either the project or the model, such as adding new project members or changing the text of the model description, the changes are not visible unless I manually refresh the page.  So I added some people to a project and then we decided to add another person, so I clicked edit a second time (and yes, I had saved the changes I made earlier) and the people that I just added were gone.  Suspecting that they really were added to the project, but weren't visible, I refreshed the page and they reappeared.  Same thing with other types of edits at both the project and model levels.  

Additionally, every new CCA model I made went to the model page where it asked me to be patient.  However, the new model was never drawn and I wasn't able to get it without refreshing the page.  I thought that we'd already added some code to update pages to reflect changes (replacing our websocket functionality).  Either that hasn't happened, or it has a bug, but this is an important function to replace since people will think that the server is having performance issues or is down.  This was on both Windows and OS X.  I'm not seeing the model drawing problem on Windows for a Parameter Space model (with either a local or a remote input file), which surprises me since I thought that the code was shared with CCA.

**Comment by Mletter1** [comment]
#745 took care of the edit button

**Comment by Mletter1** [comment]
there are still some linger results from this, timeseries is the example that comes to mind

**Comment by Mletter1** [comment]
I'm going to close this issue and make a new one specifically for timeseries see #754
