### ISSUE TITLE
Delete project button visible to non-administrators

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#778]
Presumably only a project administrator has the ability to delete the project.  Consequently, non-administrators should not see the 'Delete' button at the project level.  As a non-administrator, I can click on it and enter into the deletion dialog, though when I click the button to confirm 'Delete Project', nothing happens (so we are checking my role at this point).  Although I can't actually delete the project, the dialog remains.  Rather than adding error messages to let me know what happened and why, I think it is cleaner to remove the 'Delete' button altogether (just as we do the 'Edit' button now).

**Comment by alexsielicki** [comment]
I tested all combinations of roles across models, projects, and the site root and found other problems. Here's a summary:
1. Readers get "Create Model" functionality at the project level, however it does not work.
2. Readers get "Create Model" functionality at the model level, however it does not work.
3. Readers get "Create New Bookmark", "Edit Bookmark", and "Delete Bookmark" functionality at the model level, however it does not work.

Working on resolving all these.
