### ISSUE TITLE
Categorical filters need tooltips when values are truncated

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#789]
<img width="130" alt="screen shot 2017-11-09 at 12 13 52 pm" src="https://user-images.githubusercontent.com/66206/32624788-8da61552-c547-11e7-8da3-81832b429400.png">

Values could be impossible to discerns when truncated. We should add tooltips when the values are too long to display in their entirety.

**Comment by alexsielicki** [comment]
@pjcross, what do you think? Should I fix this while I'm in this part of the code already?

**Comment by pjcross** [comment]
yes.

**Comment by alexsielicki** [comment]
I made it so the tooltips only show up if the label has been truncated. When the full label is visible, there is no tooltip. This is consistent with how the SlickGrid table works.

**Comment by pjcross** [comment]
perfect
