### ISSUE TITLE
Slider endpoint threshold values don't match endpoint labels 

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#791]
When moving the slider endpoint, sometimes rounding on the values leads to points being excluded that the user would expect to have as included points (i.e. their value is equal to the endpoint label, yet they are not in the set of visible points).  This occurs because the actual value from the slider is slightly off of their value, so they fail the boundary condition, yet the label is being rounded to a value that appears to set a different boundary condition that those points should meet.

**Comment by alexsielicki** [comment]
Solved this by displaying full precision slider endpoint values when hovering over a filter. Now working on making those values editable by typing instead of just sliding with mouse.
