### ISSUE TITLE
Hyperchunks not working

### ISSUE THREAD

**Issue by smartin71** [sandialabs/slycat#797]
The expression "0/0/0|3" gets only the 0th piece, where it should get the 0th and 3rd pieces.

For example:

slice_data = slycat.web.server.get_model_arrayset_data (
            database, model, "dac-var-data", "%s/0/0|3" % database_ind)[0]

returns only the 0th row, not the 0th and 3rd rows.

Note that if I use "::2" or other expressions with ":"s it does work.

**Comment by Spurs20** [comment]
slice_data = slycat.web.server.get_model_arrayset_data (
database, model, "dac-var-data", "%s/0/0|3" % database_ind)[0]

Will only return the 0th piece.

slice_data = slycat.web.server.get_model_arrayset_data (
database, model, "dac-var-data", "%s/0/0|3" % database_ind)[1]

Will return the 3rd piece.
