### ISSUE TITLE
RETURN key removes proj admin during project membership edit

### ISSUE THREAD

**Issue by wlhunt** [sandialabs/slycat#798]
The return or enter key unexpectedly removes a member (often the first in the list which is the proj admin) when depressed during an add-member operation.

To re-create this:
-open the edit project dialog
-type something in the username field
-hit the enter key

The first user in the list below (probably the project admin) has been removed. If the list contains multiple names it may be difficult to recognize that the admin was just removed. When the SAVE button is pressed those changes are made.

I'm including 3 screenshots of that sequence.

![addmem1](https://user-images.githubusercontent.com/4999986/34743550-520f0442-f547-11e7-98c0-5f872e552865.PNG)

![addmem2](https://user-images.githubusercontent.com/4999986/34743558-56fa39a4-f547-11e7-8328-a1389cffa7fd.PNG)

![addmem3](https://user-images.githubusercontent.com/4999986/34743567-60fa48e0-f547-11e7-8429-4134e58be34c.PNG)

**Comment by Spurs20** [comment]
Fixed this in commit ad70595 by suppressing the default key binding for Enter key

**Comment by Spurs20** [comment]
Resolved this by suppressing the default binding for the Enter key
