### ISSUE TITLE
Replace slickGrid with a component that is still being maintained

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#821]
SlickGrid is no longer maintained. We might want to replace it someday with a grid that's still being maintained. One good option seems to be ag-Grid:
https://www.ag-grid.com

**Comment by alexsielicki** [comment]
I replaced it with a fork that's actively being maintained as of February 2019:
https://github.com/6pac/SlickGrid

**Comment by pjcross** [comment]
It's great that you found this!

**Comment by Mletter1** [comment]
lets check out https://www.ag-grid.com/best-react-data-grid/

**Comment by alexsielicki** [comment]
@Mletter1 also found this, which looks good:
https://react-bootstrap-table.github.io/react-bootstrap-table2/
