### ISSUE TITLE
Colors dropdown regression in new react component

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#824]
The colors dropdown has regressed somewhat during the conversion to react:

- Border needs to be rounded instead of square.
- Label needs to be "Colors" instead of "Color Scheme".
- Spacing to the left needs to be consistent with what's used between other button sections. It's currently too wide.
- When a model loads, the currently active color scheme needs to be highlighted in blue. Currently, it does not highlight until it's changed.
- The blue highlighting for current color scheme needs to go all the way across each select item, not just under the text part.

**Comment by alexsielicki** [comment]
@Spurs20, I just fixed the issue with the square border around the Colors dropdown. Also changed its name while I was in there. Giving the rest back to you.

**Comment by Spurs20** [comment]
Commits b2f97a4, 058166f, and 467c662 take care of this.
