### ISSUE TITLE
Log scale axes are not log values

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#846]
When switching to log scale, the markings are greatly reduced, both the ticks along the axes and the values along the legend.  Here is the non-log scale rendering:

![image](https://user-images.githubusercontent.com/4998608/49893583-09f4d080-fe09-11e8-9456-fa82ce731100.png)

Here is the log scale version:

![image](https://user-images.githubusercontent.com/4998608/49893731-5dffb500-fe09-11e8-9367-3880297dd6ac.png)

**Comment by alexsielicki** [comment]
As we discussed, only the scale is updated in D3, not the values.

I will look into putting more tick labels on log scales.
