### ISSUE TITLE
Hide/Show Selection Or Adding Filter Erases X Axis Label

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#848]
When I hide or show a selection using the Selection Action, the X Axis label disappears.  Same thing happens when I add a filter.

**Comment by pjcross** [comment]
Turning off auto scaling also triggers the problem

**Comment by alexsielicki** [comment]
This was caused by updates to the x_axis not triggering an update to the x_axis label. I changed the code that updates the x_axis to also updated the x_axis label, so we shouldn't see this issue again.
