### ISSUE TITLE
Adjusting column widths in tables stopped working

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#849]
True for both Firefox and Chrome on both Windows and OS X.

**Comment by alexsielicki** [comment]
I will try a different version of slickgrid to correct this:
https://github.com/6pac/SlickGrid

**Comment by alexsielicki** [comment]
Here's a link to its NPM repo:
https://www.npmjs.com/package/slickgrid

And another similar NPM repo that I should sort out:
https://www.npmjs.com/package/slickgrid-plus
