### ISSUE TITLE
Table Column Sort Loses Sorted Column and Columns to Right of It 

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#853]
In the Data Centric update, on Firefox on Windows for the diode clipper data in a Parameter Space model, I got the following when I sorted on the first output column:
![image](https://user-images.githubusercontent.com/4998608/52751309-3f09d480-2fac-11e9-8544-dcdc876ac0c8.png)
Refreshing the browser page restores the data.  I've been unable to reproduce the error since.

**Comment by pjcross** [comment]
I can't reproduce this, so I'm closing it for now

**Comment by pjcross** [comment]
It just happened again.  I had just turned off the scaling icon...
![image](https://user-images.githubusercontent.com/4998608/52980631-53791300-3398-11e9-9dec-39a3267e7603.png)
This was a newly created Parameter Space model, also from the diode clipper data.

**Comment by alexsielicki** [comment]
This might have been fixed with the SlickGrid update. @pjcross, were you seeing this on Firefox only, or also in Chrome?

**Comment by pjcross** [comment]
I think it was fixed.  I can't produce it now on either Firefox or Chrome.  I'm pretty sure that I was originally seeing it in Firefox (I don't think that I had tested it against Chrome yet).
