### ISSUE TITLE
Table Wraps Headers (Windows and Firefox, but not Chrome)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#862]
With a large number of columns (Milestone data), although scrolling is enabled and not all of the columns are visible in the window, some of theme wrap around in Firefox.  I can select the last header and the appropriate (offscreen) column highlights accordingly:
![image](https://user-images.githubusercontent.com/4998608/53210943-ce426800-35fc-11e9-8424-9f60ef7c9c14.png)
I think that part of the problem is that the header widths are decoupled from the table column widths.  This appears to be in the tables of all the models.

**Comment by pjcross** [comment]
I think that the following is related to this general table issue:
![image](https://user-images.githubusercontent.com/4998608/53212282-a4d80b00-3601-11e9-95a4-479f88b96204.png)
For a non-standard version of the cars data, I tried to make the column wider (which still is broken), then I tried to sort the column, which produced the peculiar results above (blank columns and columns that are slivers).

**Comment by alexsielicki** [comment]
I'm unable to reproduce this. Wondering if it was being caused by a caching issue. Can you clear your cache and try again please?

**Comment by pjcross** [comment]
I've tried doing a shift+refresh and I've turned the disable cache on in the developer tools.  Nothing changes:
![image](https://user-images.githubusercontent.com/4998608/53367156-aad03380-3902-11e9-9ad3-a96d0d0a63f3.png)

**Comment by alexsielicki** [comment]
This looks fixed to me on qual using Firefox ESR 60.5.2, which was showing the problem on my Mac before I upgraded SlickGrid.
