### ISSUE TITLE
Edit Axes Scales has unneccessary scrollbar

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#869]
Although all of the variables for the axes are visible, the dialog has a scrollbar:
![image](https://user-images.githubusercontent.com/4998608/53513349-302e2200-3a82-11e9-8f06-1bb31d877e6b.png)
Perhaps this is due to the table having more columns than are shown (links to images & videos), but the count of columns that can be used as axes is much smaller.

**Comment by alexsielicki** [comment]
I can't reproduce this in FF or Chrome on Mac. @pjcross, are you seeing this on Windows only? Which browsers are affected?

**Comment by alexsielicki** [comment]
I think this is due to Bootstrap 4 handling long modals in a different way than version 3. I will update this modal to take that into consideration. With long variable lists, you'll be able to scroll the modal, which will extend past the bottom of the viewport.

**Comment by alexsielicki** [comment]
@Spurs20 can you verify that this is fixed on FF on Mac? Thanks
