### ISSUE TITLE
Input Metavariable Label Misaligned

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#871]
The following label misalignment occurs until you resize the CCA model.  Opening and closing the various view panels doesn't change it, only resizing the window as a whole will cause it to redraw in the proper alignment.
![image](https://user-images.githubusercontent.com/4998608/53529568-3c2dda00-3aaa-11e9-97e5-f6b10b2c47fc.png)
The problem can be recreated by doing a Reset Model through the Edit menu.  I'm only seeing this in Firefox (windows), not on chrome.

**Comment by alexsielicki** [comment]
@pjcross, have you seen this in FF? Or only Chrome? I can only reproduce it in Chrome, and only if the model page is rendered while I'm on a different tab.

**Comment by pjcross** [comment]
Yes, I see this in FF.  I'm not sure if the testing servers have been updated since your commit, but the problem is still there today.

**Comment by alexsielicki** [comment]
I can now reproduce on Firefox on Mac after resetting model

**Comment by pjcross** [comment]
I have tested in FF and Chrome (on Mac) to verify that it is fixed.
