### ISSUE TITLE
Hover not pulling media files from cluster (Firefox & Chrome on Windows)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#872]
In the new Data Centric code with the Bootstrap upgrade, hovering no longer pulls media files from the cluster.   This is also true with the testing server and the updated software stack.  I've disabled the cache in the debugger and done a shift refresh - none of these makes a difference.

**Comment by pjcross** [comment]
Looking at the problem this morning with the debugger in network mode, I'm not seeing any traffic going out when I hover over a point.

**Comment by alexsielicki** [comment]
Very strange. I fixed this issue earlier, but prod is running old code. Here's the JS code on qual:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/66206/53653345-f5ea8f00-3bff-11e9-9c76-3725c47ca245.png">

But this is what I'm showing in the source code:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/66206/53653425-1d415c00-3c00-11e9-843d-0deb243145a7.png">

@wlhunt or @Mletter1, can you check the source code sitting on qual, line 1692 of parameter-image-scatterplot.js:
https://github.com/sandialabs/slycat/blob/8144d34b787f4aae8e8e71eb612fdc7c963fd1d0/web-server/plugins/slycat-parameter-image/js/parameter-image-scatterplot.js#L1692

It should have .length, not .size(). It was changed on Feb 27, so maybe we just need another update to qual?
https://github.com/sandialabs/slycat/commit/2fe9a910ed92af1adbe9a7365df31aaba32330c9#diff-507b820f437c9ad732621d26c80c9143

**Comment by wlhunt** [comment]
I checked this and the code is still “.size”. We need to push an update to qual so we’re not testing with old code/fixed bugs.

W

**Comment by wlhunt** [comment]
I’m gonna go ahead and do a full update to everything but the cluster code. See if this resolves the issues.

I will be taking the updated code from all master branches (slycat, Videowarm, and DAC). And also pushing out an updated client from the same code

-Matt Letter

From: <owner-wg-slycat-developers@sandia.gov> on behalf of "Hunt, Warren L" <wlhunt@sandia.gov>
Reply-To: "Hunt, Warren L" <wlhunt@sandia.gov>
Date: Friday, March 1, 2019 at 11:32 AM
To: sandialabs/slycat <reply@reply.github.com>, sandialabs/slycat <slycat@noreply.github.com>
Cc: wg-slycat-developers <wg-slycat-developers@mailgate.sandia.gov>
Subject: RE: [EXTERNAL] Re: [sandialabs/slycat] Hover not pulling media files from cluster (Firefox & Chrome on Windows) (#872)

I checked this and the code is still “.size”. We need to push an update to qual so we’re not testing with old code/fixed bugs.

W

**Comment by alexsielicki** [comment]
Thanks @wlhunt, that seems to have fixed it.
