### ISSUE TITLE
Redirect Wierdness

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#873]
Although this has now stopped happening, I want to record it.  I made a number of Parameter Space models.  Each time I did, the new model would start to draw (slowly, so network speed could be a factor) and I'd see the outlines of the panels, then it would suddenly redirect me to the slycat project's page (not even the project that I'd been working it).  Going back to my project, I could see the new model, but clicking on the model caused me to bounce back to the top level page again.  This happened a bunch of times.  It seems similar to what Matt and I agreed upon for the resolution of invalid model URL's, but without the popup to tell me that it wasn't a valid model.  The first 3 model attempts were done from a data-centric saved table, the last one from a remotely ingested table (though the data table was the same across all 4).  I got Warren to watch the log while I was generating the 4th table and during one access attempt to view the model, it did draw, so the model is truely there.  But then it went back to bouncing me to the project page.  Turning on the debugger with disable cache and doing a shift refresh initially was inconclusive (sometimes I still bounced), but then the network seemed to speed up (it had been terribly slow originally).  Now I can't reproduce it.  This was all happening in Firefox on Windows.

**Comment by pjcross** [comment]
I saw this again today.  Turning on the debugger seems to have halted it.

**Comment by Spurs20** [comment]
Closing this because it couldn't be recreated.
