### ISSUE TITLE
Parameter Space Variable Dialog Lacks Scrollbar, Can't Click Continue at Bottom (Firefox on Windows 10)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#888]
When creating a Parameter Space model, if the number of variables exceeds the screen height, the dialog disappears off the bottom of the window (along with the submit button on the bottom).  Scrolling doesn't work, so the model cannot be generated.

**Comment by pjcross** [comment]
Also, when I first read in the file, it brings up the dialog, but with the following error message over the top:
![image](https://user-images.githubusercontent.com/4998608/56303243-c2ed5380-60f8-11e9-8754-d96cd9cb0554.png)
I don't see the error message in Chrome, nor is the scrolling missing.  So this is only a Firefox problem.

**Comment by alexsielicki** [comment]
Fixed by b8169c3da261d9eb881e312c59c1ba31c36a5e79
