### ISSUE TITLE
Allow deleting models from project view

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#893]
Allow the user to delete one or multiple models from the project view. Currently user needs to go into each model to delete it. This is inefficient and can be frustrating when deleting many models. 

A couple of proposed approaches:

- Add a trash can button on each model's listing on the project view. Clicking it would pop up a confirmation dialog and then delete that model.
- Have check boxes for each model then a "delete selected models" option, also with a confirmation dialog. This would allow deleting multiple models at once. It could also be expanded to other actions, such as Change Marking, Reset Model, Apply Template.

**Comment by Mletter1** [comment]
@alexsielicki I'm gonna pick this up
