### ISSUE TITLE
Add Interface for variable alias labels to Edit Axes 

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#907]
Change 'Edit Axes Scale' to 'Edit Axes', using tabs to separate the current scale controls and the alias table GUI.  The alias table will show the original variable names contained in the input table in one column and the aliases in another column that can be edited.  The aliases will be initialized to the original names from the input table, so that those values will be used in cases where the user chooses not to create an alias.  The aliases will be used in all parts of the interface (axes labels, legend, filter labels, drop down lists of variables, and table column headers).

**Comment by alexsielicki** [comment]
Perhaps we should consider calling the Edit Axes button 'Display Settings' to better reflect that it affects display settings instead of just axes, since it will not affect the table columns and the display of variable labels across the rest of the UI.

**Comment by pjcross** [comment]
Yes, sounds good.

**Comment by pjcross** [comment]
I was testing this with the intent of closing it out, but I have found one tiny bug:  when I add an apostrophe to the label (as in young's modulus to replace young_1 in our milestone data set), it is correct in the column header, but the label shown by hovering over the column header (since it is too long for all of the label to be visible) has a bunch of junk characters instead of the apostrophe.  It says young&#x27;s instead.
