### ISSUE TITLE
Login tab in VS wizard not providing feedback

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#917]
@smartin71 reports:

> I've been testing the VS wizard, and it seems like the login tab isn't working very well.  It doesn't say "Connecting ..." anymore and if you type the wrong password or make some other mistake it never tells you anything.  No feedback.

We should check this in other models since they mostly reuse the same component, so this issue could be happening across all wizards.

**Comment by pjcross** [comment]
I'm wondering if this is connected to issue #825 ?

**Comment by Mletter1** [comment]
issue #825 is unrelated

**Comment by Mletter1** [comment]
I'm closing this, @Spurs20 and I tested this on all the model creation wizards. Cannot replicate any of these issues
