### ISSUE TITLE
In 'Selection Action' only Selected points can be restored

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#924]
In 'Section Action', if I select 'Hide Unselected', then I select 'Show' to restore them, they are not restored.  I can get only them back by clicking 'Show All'.  However, if I select 'Hide' and then 'Show', the selected points are hidden and restored.  It seems that the interpretation of the commands has shifted to only act on the selected points, whereas in the past (and I think that I remember it working this way at one time), selecting 'Show' would reveal the last set of hidden points, whether they were selected or not.  It differed from 'Show All' in that you might go through a succession of point hiding operations (sometimes hiding the selected points and perhaps sometimes hiding the non-selected points) to reduce the visible points.  'Show' undoes the last 'Hide' operation (of whichever sort), whereas 'Show All' resets to start over with all points visible.

**Comment by alexsielicki** [comment]
Change the Selection Action menu to contain these items:

_Selected Items_
- Hide
- Show
- Pin

_Unselected Items_
- Hide
- Show

The new show unselected items functionality will show whatever is unselected.

**Comment by alexsielicki** [comment]
@pjcross, Hide Unselected currently shows any items that were selected when the command was executed. See:
https://github.com/sandialabs/slycat/blob/7e1f75d83050112798a43ff561af8e2fb1acdc60/web-server/plugins/slycat-parameter-image/js/ui.js#L1044-L1050

For example, select a set of rows in the table that includes both hidden and visible rows. Now click Selection Action > Hide Unselected. Notice that any selected hidden rows are not visible. 

Is this how you'd like it to keep working? Seems odd to me that we are altering the visibility of the selection when the command seems like it should only affect the unselected rows. This also has implications for the new Show Unselected functionality. Should it also affect the selected rows by hiding them?
