### ISSUE TITLE
Pin Selection Action Disabled When Filters Are Present (Windows/Firefox)

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#930]
Although filtering and hide/show of selected points have conflicts in terms of determining what should be visible, pinning of selected points should be enabled during filtering.  However, if a filter is present, the pinning function within 'Selection Action' is disabled.  Removing the filter reenables it and the images are then retrieved.

**Comment by alexsielicki** [comment]
I'm enabling pinning when filtering is happening. However, you still won't be able to pin simulations that are hidden by filters, even if they are selected in the table. For example, if you have selected simulations 1 and 3, but 3 is filtered out, only 1 will be pinned.

**Comment by alexsielicki** [comment]
Also, I'm disabling (i.e., graying out) the pin item in the dropdown if there is no selection or if all items in the selection are also hidden by the current filters.
