### ISSUE TITLE
Redo Selection Action menu

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#940]
Goal is to consolidate more actions into this menu to free up space for 3D controls. Rename menu to _Actions_. Move _Show All_ and _Close All_ inside the menu per below layout. Add a _Select All_ option that selects all simulations that are already pinned.

### Actions

- Show All

**Selected Items**
- Hide
- Show
- Pin

**Unselected Items**
- Hide Unselected
- Show Unselected

**Pinned Items**
- Close All
- Select All

**Comment by pjcross** [comment]
The earlier related issue was #816 (in case you want to see it).  Since this redesign subsumes it, I'm going to close it now.

**Comment by alexsielicki** [comment]
Thanks @pjcross 

Per your comment in #816, I could use this alternative menu instead of the first one. Which one do you prefer? I kind of like this one better since it keeps all pin related actions together.

### Actions

- Show All

**Selected Items**
- Hide
- Show

**Unselected Items**
- Hide Unselected
- Show Unselected

**Pins**
- Pin Selected Items
- Select All Pinned Items
- Close All Pins

**Comment by pjcross** [comment]
I like this one better too.  Not only does it keep the Pin operations together, but it makes the selected/unselected groups be symmetric.  It bothered me in the earlier one that they weren't corresponding in their operations.
