### ISSUE TITLE
Data Min and Data Max don't reflect changes to variable made through Actions > Edit Variable Values until the model is reloaded.

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#963]

**Comment by Mletter1** [comment]
This is done in the parser so if you update something in the table that changes min and max values you would need to overwrite the old ones with the new values in datatable for them to show up correctly.

**Comment by alexsielicki** [comment]
Hi @Mletter1, it looks to me like the following components react properly to a min/max edit:

-  scatterplot
- table
- variable ranges

However, filters seem to get stuck on the original min/max values. Is this what you're seeing too? Any other components that are not reacting properly to data edits?

**Comment by alexsielicki** [comment]
After digging into filters more, they also seem to react to min and max changes, but sometimes in a not entirely clear way. I will demo and explain at our next meeting.

**Comment by alexsielicki** [comment]
@Mletter1 ignore my comment to you from yesterday. I thought this was a new issue you filed. But now see this is an old issue that you commented on. Closing it because it's already been fixed at some point.
