### ISSUE TITLE
Behavior of Synch in 3D Viewer is Inconsistent 

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#969]
The color map selection IS synched across views regardless of whether synching is enabled or not.  The variable selected to color code the surface by IS NOT synched across views regardless of whether synching is enabled or not.  The synch button seems to only control whether object movement and the viewing frustum across views are synched.  I would expect that when synch is enabled, it means that the variable and the color map are also synched to the focus view.  If I want to change the variable that I am color-coding by, and I have 6 viewers up, I don't want to have to change the variable in each one separately.  It seems unlikely that I would want to view different variables between views, because I would only be able to compare them between different runs (more of an apples to oranges comparison).  Since the color map is shared between all views, irrespective of whether synch is enabled, I think it would make sense to have the variable value be shared between all views as well to keep the behavior consistent and facilitate group changes across the views.

**Comment by alexsielicki** [comment]
Since the variables in each view can be different, we decided to sync the variables across views only when sync is enabled. I will read the color by variable from the currently active pin and try to apply that same variable to all open pins. If it's missing in any of the open pins, I will simply skip it, leaving its current variable unchanged.

**Comment by pjcross** [comment]
Perhaps this should be a separate issue, but I've just noticed that in two synchronized views that the front and back clipping planes differ based on which one is the focus view.  The focus view displays the entire object, but the synchronized second view is frequently clipped from either the front or the back part of the object as you zoom in and out.

**Comment by alexsielicki** [comment]
After user feedback, we are leaving this as is. User wants to be able to compare different variables in duplicate windows of same 3D media.
