### ISSUE TITLE
Add Legend for 3D Viewer Surface Coloration

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#971]
Users need a way to interpret the color-coding of surfaces in the 3D viewer.  A legend in each viewer would take up too much of the screen real estate, so an additional legend should be added to the Parameter Space scatterplot view.  Since we already have a legend for the point color-coding, adding an icon to each legend (use the same 3D icon as for the synch button to the new legend, not sure for the scatterplot legend, but something that gives a visual sense of a scatterplot, maybe a cluster of points).  Since we don't have global information for variable ranges in the 3D models, the 3D legend will only describe the viewer that is currently in focus and it will be updated every time the focus is changed (so in addition to the 3D icon, perhaps the run's identifier can also be added to the legend to reinforce the idea that the legend only applies to that view).

**Comment by alexsielicki** [comment]
Per user feedback, need to add a separate legend to each 3D viewer pane. Have it size itself vertically same as pane and allow resizing with pane. Minimize horizontal size, but maintain variable label, color gradient, and axis with labels, in that order from left to right.

**Comment by pjcross** [comment]
This has been implemented.
