### ISSUE TITLE
Remote file download times out

### ISSUE THREAD

**Issue by Mletter1** [sandialabs/slycat#981]
Currently uploading a remote file times out because it has 1 "file part" so for large files the time out on the ajax call will trip well sftp is running and downloading the remote file.

suggestions:
- This operation need to be move to some sort of threading mechanism so we can keep downloading the file and respond to the ajax call at the same time
- Need to add new thread monitoring mechanism for when the thread is running sftp.

**Comment by pjcross** [comment]
I believe that this was in response to being unable to read in the 15K run Milestone csv.  I have never gotten this to work, have you?  Since we currently can't ingest even 1001 run Milestone csv, I can't test this to verify that it works.

**Comment by pjcross** [comment]
I'm closing this in favor of #1057, since the problem with the 15K Milestone CSV is not one of hanging, but a parsing problem instead.
