### ISSUE TITLE
In 3D synchronized views, the front and back clipping planes differ based on which one is the focus view

### ISSUE THREAD

**Issue by alexsielicki** [sandialabs/slycat#986]
The focus view displays the entire object, but the synchronized second view is frequently clipped from either the front or the back part of the object as you zoom in and out.  When you change the focus to the clipped view, all parts of it become visible as you zoom, whereas the formerly complete object in the first focus view is now being clipped.  It looks as though the focus view has a different viewing frustum than the secondary views.

_Originally posted by @pjcross in https://github.com/sandialabs/slycat/issues/969#issuecomment-652050246_

**Comment by pjcross** [comment]
I've been looking at this, and in slycat/web-server/plugins/slycat-parameter-image/js/vtk-camera-synchronizer.js, in function handleModifiedCamera (), there are a number of settings that are copied from the focal camera to the others:
        targetCamera.camera.setPosition(...sourceCamera.getPosition());
        targetCamera.camera.setFocalPoint(...sourceCamera.getFocalPoint());
        targetCamera.camera.setViewUp(...sourceCamera.getViewUp());

I think that you need to add:
        targetCamera.camera.setClippingRange(...sourceCamera.getClippingRange());

Here's the documentation link: https://kitware.github.io/vtk-js/api/Rendering_Core_Camera.html

**Comment by alexsielicki** [comment]
Just added the clipping range to the camera synchronizer in 23e84d2ba6e278110d28f9682542da8d7be0b560

It doesn't help with very different object, for example, planet earth and a cylinder. But might work with identical objects from different simulations. Either way, it doesn't seem to have any negative implications.

@pjcross, give it a try and let me know if this needs more attention.

**Comment by pjcross** [comment]
This is happening again.
