### ISSUE TITLE
Need to Display TimeValue in 3D Viewer

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#996]
In the vtp files, “TimeValue” is the keyword for the simulation time value for the surface mesh.  The RangeMin/RangeMax values (they are the same in our examples) show the timevalue for the timestep of the mesh.  This value needs to be included somewhere in the view.  I think a format of 'Time: xxxx', where xxxx is the e-notation time value.

In vtk.js, the easy way to display it is using LabelWidget: https://kitware.github.io/vtk-js/examples/LabelWidget.html.  This widget allows the user to reposition the label by dragging, so if it is obscuring part of the geometry it can be moved out of the way.

**Comment by alexsielicki** [comment]
I can see the TimeValue DataArray in the vtp file. Nested under a couple other elements like so:

    <VTKFile>
      <PolyData>
        <FieldData>
          ...
          <DataArray type="Float64" Name="TimeValue" NumberOfTuples="1" format="appended" RangeMin="..." RangeMax="..." offset="..." />
          ...

I haven't found a way to read it or its RangeMin or RangeMax attributes using the [vtk XMLPolyDataReader](https://kitware.github.io/vtk-js/api/IO_XML_XMLPolyDataReader.html) yet, but I'm working on it.

**Comment by alexsielicki** [comment]
@pjcross would you like the font size and family for these labels to match what the user specified in Display Settings > Axes Scales?
