### ISSUE TITLE
Shared Ranges for Color Maps in 3D Viewers

### ISSUE THREAD

**Issue by pjcross** [sandialabs/slycat#997]
Currently, the color mapping in each 3D viewer is done independently, where the range of the variable value being used to color the surface is mapped to two extremes of the color lookup table.  Since the variable ranges will be different between simulations, a particular shade of red will most likely be encoding a different value in each viewer.  This skews the comparison.  The color values need to map to the same variable values across the views (assuming that the same variable is being rendered).  The user needs a method to set the variable ranges for 3D surface color-coding.  I would propose adding another tab to our 'Display Settings' utility.  This could be '3D Variable Ranges', which would only be present if .vtp files are in the CSV table.  It would be similar to the 'Variable Ranges' interface, though we would have the LUT Min and LUT Max instead of the Axis Min and Max (hopefully LUT doesn't need to be spelled out).  However, since we don't want to have to read in each .vtp to find out the Data Min and Max across the ensemble, how do we set the range if the user hasn't specified a LUT Min/Max?  What is our default range?  Plus, it might be useful for the user to have even partial information about the true data ranges.  Could we do a lazy evaluation?  Could we keep a running min/max across just those variables that have been displayed within only those vtp files that have already been viewed?  Then we could populate the Data Min/Max with those values.  Unless or until the user enters their own LUT Min/Max values, these value ranges would be used to normalize the color ranges between views.  It would mean that the ranges might shift as new min/max values are encountered (so the meaning of a particular shade would change over time), but the colors being compared at any one time would be consistent across views.

**Comment by alexsielicki** [comment]
@pjcross can all this be saved in the bookmark? Or do we need to save it to the model so it persists across users and across devices?

**Comment by pjcross** [comment]
It really should be saved in the model so that collaborators can see it.  Otherwise, I can imagine all sorts of confusion when project members don't realize that the range has been shifted, so they do see the same results as their collaborators.

**Comment by alexsielicki** [comment]
We decided to save it in the bookmark since it's easier to implement and can still be shared among collaborators. Also, will add checkbox to each variable so that users can disable this feature on a variable level, as well as a "check all" feature.

**Comment by alexsielicki** [comment]
This is now completed. There will probably be refinements to it in the future and we can open new issues for those.
